#define MAINMENU 0  	/* TREE */
#define MENUABOU 12  	/* OBJECT in TREE #0 */
#define MENUQUIT 21  	/* OBJECT in TREE #0 */
#define MENUNEW 23  	/* OBJECT in TREE #0 */
#define MENUSAVE 25  	/* OBJECT in TREE #0 */
#define MENUOPEN 24  	/* OBJECT in TREE #0 */
#define MENUSVAS 26  	/* OBJECT in TREE #0 */
#define MENUEDIT 5  	/* OBJECT in TREE #0 */
#define MENUFILE 4  	/* OBJECT in TREE #0 */
#define MENUWND 9  	/* OBJECT in TREE #0 */
#define MENUFX 7  	/* OBJECT in TREE #0 */
#define ALNOMEM 0  	/* STRING */
#define ALZXFON 1  	/* STRING */
#define ALFORMAT 2  	/* STRING */
#define ALZXFON2 3  	/* STRING */
#define ABOUTBOX 1  	/* TREE */
#define ABOUTOK 2  	/* OBJECT in TREE #1 */
#define APPICON 4  	/* OBJECT in TREE #1 */
#define ALNOFONT 4  	/* STRING */
#define MENUDESK 3  	/* OBJECT in TREE #0 */
#define ALNOWIN 5  	/* STRING */
#define ALNOWING 6  	/* STRING */
#define ALDIRTY 7  	/* STRING */
#define MENUTILE 54  	/* OBJECT in TREE #0 */
#define MENUCASC 55  	/* OBJECT in TREE #0 */
#define NEWFONT 2  	/* TREE */
#define SET1 3  	/* OBJECT in TREE #2 */
#define SET2 4  	/* OBJECT in TREE #2 */
#define SET3 5  	/* OBJECT in TREE #2 */
#define SPMINUS 9  	/* OBJECT in TREE #2 */
#define SPPLUS 8  	/* OBJECT in TREE #2 */
#define NEWOK 11  	/* OBJECT in TREE #2 */
#define NEWCNCL 12  	/* OBJECT in TREE #2 */
#define SET0 10  	/* OBJECT in TREE #2 */
#define DLGSVAS 3  	/* TREE */
#define SVAS1 7  	/* OBJECT in TREE #3 */
#define SVAS2 8  	/* OBJECT in TREE #3 */
#define SVAS3 11  	/* OBJECT in TREE #3 */
#define SVAS4 9  	/* OBJECT in TREE #3 */
#define SVAS5 10  	/* OBJECT in TREE #3 */
#define SVASOK 13  	/* OBJECT in TREE #3 */
#define SVASCNCL 14  	/* OBJECT in TREE #3 */
#define NEWBOX 2  	/* OBJECT in TREE #2 */
#define ALFSIZE 8  	/* STRING */
#define MENUCUT 28  	/* OBJECT in TREE #0 */
#define MENUCOPY 29  	/* OBJECT in TREE #0 */
#define MENUPAST 30  	/* OBJECT in TREE #0 */
#define MENUSELA 32  	/* OBJECT in TREE #0 */
#define MENUFXRH 38  	/* OBJECT in TREE #0 */
#define MENUFXRV 39  	/* OBJECT in TREE #0 */
#define MENUFXRC 41  	/* OBJECT in TREE #0 */
#define MENUFXRA 42  	/* OBJECT in TREE #0 */
#define MENUFXMU 44  	/* OBJECT in TREE #0 */
#define MENUFXMD 46  	/* OBJECT in TREE #0 */
#define MENUFXML 45  	/* OBJECT in TREE #0 */
#define MENUFXMR 47  	/* OBJECT in TREE #0 */
#define MENUFX2 8  	/* OBJECT in TREE #0 */
#define MENUBOLD 49  	/* OBJECT in TREE #0 */
#define MENUITAL 50  	/* OBJECT in TREE #0 */
#define MENUUL 51  	/* OBJECT in TREE #0 */
#define MENUINV 52  	/* OBJECT in TREE #0 */
#define DLGPREFS 4  	/* TREE */
#define COL0 5  	/* OBJECT in TREE #4 */
#define COL16 22  	/* OBJECT in TREE #4 */
#define GREY0 40  	/* OBJECT in TREE #4 */
#define MENUPREF 34  	/* OBJECT in TREE #0 */
#define PREFOK 48  	/* OBJECT in TREE #4 */
#define PREFCNCL 49  	/* OBJECT in TREE #4 */
#define SVASBOX 6  	/* OBJECT in TREE #3 */
#define ALPSF2 9  	/* STRING */
#define SVAS6 12  	/* OBJECT in TREE #3 */
#define ALNOFON 10  	/* STRING */
#define DLGTRANS 5  	/* TREE */
#define TRANSC1 4  	/* OBJECT in TREE #5 */
#define TRANSC2 5  	/* OBJECT in TREE #5 */
#define TRANSC3 8  	/* OBJECT in TREE #5 */
#define TRANSC4 6  	/* OBJECT in TREE #5 */
#define TRANSC5 7  	/* OBJECT in TREE #5 */
#define TRANSC6 9  	/* OBJECT in TREE #5 */
#define MENUFONT 6  	/* OBJECT in TREE #0 */
#define TRANSBOX 3  	/* OBJECT in TREE #5 */
#define TRANSCNC 11  	/* OBJECT in TREE #5 */
#define TRANSOK 10  	/* OBJECT in TREE #5 */
#define MENUTRCD 36  	/* OBJECT in TREE #0 */
