#define CHGPAPER 35  	/* STRING */
#define DVCMISS 36  	/* STRING */
#define OUTINFO 0  	/* TREE */
#define SCRNPREF 1  	/* TREE */
#define PRNTPREF 2  	/* TREE */
#define OKINFO 12  	/* OBJECT in TREE #0 */
#define WAITROOT 8  	/* OBJECT in TREE #1 */
#define WAITKEY 10  	/* OBJECT in TREE #1 */
#define CYCLROOT 3  	/* OBJECT in TREE #1 */
#define YESCYCLE 6  	/* OBJECT in TREE #1 */
#define NOCYCLE 5  	/* OBJECT in TREE #1 */
#define XYZZZZZ 62  	/* OBJECT in TREE #9 */
#define OKSCRN 14  	/* OBJECT in TREE #1 */
#define CANSCRN 15  	/* OBJECT in TREE #1 */
#define PRSCROOT 4  	/* OBJECT in TREE #2 */
#define PRNTFS 6  	/* OBJECT in TREE #2 */
#define XYZZZZZZ 9  	/* OBJECT in TREE #1 */
#define FILMPREF 5  	/* TREE */
#define FILMNAM0 21  	/* OBJECT in TREE #5 */
#define OKPRNT 28  	/* OBJECT in TREE #2 */
#define CANPRNT 29  	/* OBJECT in TREE #2 */
#define PRTCNT 3  	/* TREE */
#define NUMPRTD 1  	/* OBJECT in TREE #3 */
#define CURPIC 3  	/* OBJECT in TREE #3 */
#define FILEMISS 4  	/* TREE */
#define MISSDIR 2  	/* OBJECT in TREE #4 */
#define MISSITEM 5  	/* OBJECT in TREE #4 */
#define MISSCONT 10  	/* OBJECT in TREE #4 */
#define COLRPREF 6  	/* TREE */
#define FILMTYP0 6  	/* OBJECT in TREE #5 */
#define DARKEN3 14  	/* OBJECT in TREE #5 */
#define OKCAMCOL 55  	/* OBJECT in TREE #6 */
#define CANCMCOL 56  	/* OBJECT in TREE #6 */
#define CAMCOL00 4  	/* OBJECT in TREE #6 */
#define CAMCOL15 19  	/* OBJECT in TREE #6 */
#define LGTSHADE 37  	/* OBJECT in TREE #6 */
#define DRKSHADE 46  	/* OBJECT in TREE #6 */
#define COLWHITE 23  	/* OBJECT in TREE #6 */
#define OKFLMOPT 28  	/* OBJECT in TREE #5 */
#define CANFMOPT 29  	/* OBJECT in TREE #5 */
#define FILMROOT 5  	/* OBJECT in TREE #5 */
#define LGHTROOT 13  	/* OBJECT in TREE #5 */
#define COLIROOT 3  	/* OBJECT in TREE #6 */
#define SHADROOT 36  	/* OBJECT in TREE #6 */
#define COLNROOT 22  	/* OBJECT in TREE #6 */
#define REDRGB 49  	/* OBJECT in TREE #6 */
#define GREENRGB 50  	/* OBJECT in TREE #6 */
#define BLUERGB 51  	/* OBJECT in TREE #6 */
#define SGEMEXT 0		/* FREE STRING */
#define SINFEXT 1		/* FREE STRING */
#define SLISEXT 2		/* FREE STRING */
#define SOUTEXT 3		/* FREE STRING */
#define SGMPEXT 4		/* FREE STRING */
#define SIMGEXT 5		/* FREE STRING */
#define SUNTITLD 7		/* FREE STRING */
#define COLPURPL 34  	/* OBJECT in TREE #6 */
#define COLSTR00 21  	/* OBJECT in TREE #6 */
#define COLSTR01 35  	/* OBJECT in TREE #6 */
#define COLSTR02 47  	/* OBJECT in TREE #6 */
#define COLSTR03 54  	/* OBJECT in TREE #6 */
#define COLSTR04 53  	/* OBJECT in TREE #6 */
#define COLSTR05 52  	/* OBJECT in TREE #6 */
#define SAPPNAME 8		/* FREE STRING */
#define YESFFF 10  	/* OBJECT in TREE #2 */
#define FFFROOT 8  	/* OBJECT in TREE #2 */
#define TOTCNT 2  	/* OBJECT in TREE #3 */
#define FILMNAMN 27  	/* OBJECT in TREE #5 */
#define DEVCTREE 7  	/* TREE */
#define OBJ2 48  	/* OBJECT in TREE #6 */
#define TREE25 0  	/* TREE */
#define DEVCROOT 1  	/* OBJECT in TREE #7 */
#define GLOBPREF 8  	/* TREE */
#define OKPGOPT 12  	/* OBJECT in TREE #8 */
#define CANPGOPT 13  	/* OBJECT in TREE #8 */
#define VERSNUM 5  	/* OBJECT in TREE #0 */
#define AUTODYES 8  	/* OBJECT in TREE #8 */
#define AUTOROOT 6  	/* OBJECT in TREE #8 */
#define FILETREE 9  	/* TREE */
#define FIL0NAME 1  	/* OBJECT in TREE #9 */
#define FIL0ITEM 38  	/* OBJECT in TREE #9 */
#define LOGOICON 1  	/* OBJECT in TREE #0 */
#define GEMICON 2  	/* OBJECT in TREE #0 */
#define UNSVDCHG 37  	/* STRING */
#define NOTLIST 38  	/* STRING */
#define NOOVLERR 39  	/* STRING */
#define PRNTFILM 40  	/* STRING */
#define NODSPACE 41  	/* STRING */
#define DRKSLIDE 42  	/* STRING */
#define REPLACEF 43  	/* STRING */
#define CNTLTREE 10  	/* TREE */
#define STRTITEM 12  	/* OBJECT in TREE #10 */
#define ADDITEM 13  	/* OBJECT in TREE #10 */
#define DELEITEM 14  	/* OBJECT in TREE #10 */
#define DUPLITEM 15  	/* OBJECT in TREE #10 */
#define ADDSTR0 7  	/* OBJECT in TREE #10 */
#define DELESTR0 6  	/* OBJECT in TREE #10 */
#define DUPLSTR0 5  	/* OBJECT in TREE #10 */
#define STRTSTR0 11  	/* OBJECT in TREE #10 */
#define NOSTART 44  	/* STRING */
#define HRESICNS 11  	/* TREE */
#define HLOGOICN 1  	/* OBJECT in TREE #11 */
#define HOUT1ICN 3  	/* OBJECT in TREE #11 */
#define HOUT2ICN 4  	/* OBJECT in TREE #11 */
#define HGEMICON 2  	/* OBJECT in TREE #11 */
#define HKEYAICN 11  	/* OBJECT in TREE #11 */
#define HKEYCICN 12  	/* OBJECT in TREE #11 */
#define HKEYDICN 13  	/* OBJECT in TREE #11 */
#define HKEYSICN 14  	/* OBJECT in TREE #11 */
#define HESCICON 15  	/* OBJECT in TREE #11 */
#define HSTRTICN 10  	/* OBJECT in TREE #11 */
#define ESCICON 5  	/* OBJECT in TREE #3 */
#define OUT1ICON 3  	/* OBJECT in TREE #0 */
#define OUT2ICON 4  	/* OBJECT in TREE #0 */
#define HALTICON 16  	/* OBJECT in TREE #11 */
#define ADDSTR1 8  	/* OBJECT in TREE #10 */
#define DELESTR1 9  	/* OBJECT in TREE #10 */
#define DUPLSTR1 10  	/* OBJECT in TREE #10 */
#define FILXITEM 73  	/* OBJECT in TREE #9 */
#define FILXNAME 36  	/* OBJECT in TREE #9 */
#define OBJ0 0  	/* OBJECT in TREE #5 */
#define SHORTCT1 23864  	/* TREE */
#define TREE28 23864  	/* TREE */
#define SHRTCUT2 12  	/* TREE */
#define SHRTDIAL 23864  	/* TREE */
#define SHRTCUT1 23864  	/* TREE */
#define SHRTOK 12  	/* OBJECT in TREE #12 */
#define SINFNAME 9		/* FREE STRING */
#define HPRNTICN 6  	/* OBJECT in TREE #11 */
#define HSCRNICN 7  	/* OBJECT in TREE #11 */
#define HPLOTICN 8  	/* OBJECT in TREE #11 */
#define HCMRAICN 9  	/* OBJECT in TREE #11 */
#define DEV01ICN 2  	/* OBJECT in TREE #7 */
#define SCRNICN2 1  	/* OBJECT in TREE #1 */
#define PRNTICN2 1  	/* OBJECT in TREE #2 */
#define DEV20ICN 21  	/* OBJECT in TREE #7 */
#define COPYSTXT 18  	/* OBJECT in TREE #10 */
#define COPYSTR0 17  	/* OBJECT in TREE #10 */
#define HCOPYICN 5  	/* OBJECT in TREE #11 */
#define COPYICON 19  	/* OBJECT in TREE #10 */
#define CNFMROOT 2  	/* OBJECT in TREE #8 */
#define CONFMYES 4  	/* OBJECT in TREE #8 */
#define COPYITEM 16  	/* OBJECT in TREE #10 */
#define STRTICON 20  	/* OBJECT in TREE #10 */
#define PSIZPREF 13  	/* TREE */
#define UNITROOT 4  	/* OBJECT in TREE #13 */
#define CENTUNIT 6  	/* OBJECT in TREE #13 */
#define INCHUNIT 5  	/* OBJECT in TREE #13 */
#define SIZEROOT 8  	/* OBJECT in TREE #13 */
#define LETRSIZE 10  	/* OBJECT in TREE #13 */
#define LEGLSIZE 11  	/* OBJECT in TREE #13 */
#define LEDGSIZE 12  	/* OBJECT in TREE #13 */
#define BROADSIZ 13  	/* OBJECT in TREE #13 */
#define A4SIZE 15  	/* OBJECT in TREE #13 */
#define B5SIZE 16  	/* OBJECT in TREE #13 */
#define LTSZCENT 11		/* FREE STRING */
#define LGSZCENT 12		/* FREE STRING */
#define LDSZCENT 13		/* FREE STRING */
#define A4SZCENT 16		/* FREE STRING */
#define B5SZCENT 17		/* FREE STRING */
#define LTSZINCH 19		/* FREE STRING */
#define LGSZINCH 20		/* FREE STRING */
#define LDSZINCH 21		/* FREE STRING */
#define A4SZINCH 24		/* FREE STRING */
#define TRAYPREF 14  	/* TREE */
#define PTRYICON 1  	/* OBJECT in TREE #14 */
#define PTRYROOT 4  	/* OBJECT in TREE #14 */
#define MANUFEED 7  	/* OBJECT in TREE #14 */
#define DFLTTRAY 5  	/* OBJECT in TREE #14 */
#define AUXNTRAY 8  	/* OBJECT in TREE #14 */
#define AUXNTEXT 12  	/* OBJECT in TREE #14 */
#define CONTFORM 6  	/* OBJECT in TREE #14 */
#define PORTPREF 15  	/* TREE */
#define PORTROOT 4  	/* OBJECT in TREE #15 */
#define DFLTPORT 6  	/* OBJECT in TREE #15 */
#define FILEPATH 16  	/* OBJECT in TREE #15 */
#define FILENAME 17  	/* OBJECT in TREE #15 */
#define OKPFILE 18  	/* OBJECT in TREE #15 */
#define CANPFILE 19  	/* OBJECT in TREE #15 */
#define OKPTRAY 13  	/* OBJECT in TREE #14 */
#define CANPTRAY 14  	/* OBJECT in TREE #14 */
#define OKPSIZE 17  	/* OBJECT in TREE #13 */
#define CANPSIZE 18  	/* OBJECT in TREE #13 */
#define LRESICNS 16  	/* TREE */
#define LPRNTICN 1  	/* OBJECT in TREE #16 */
#define LSCRNICN 2  	/* OBJECT in TREE #16 */
#define LPLOTICN 3  	/* OBJECT in TREE #16 */
#define LCMRAICN 4  	/* OBJECT in TREE #16 */
#define PORTICON 1  	/* OBJECT in TREE #15 */
#define CMRAICN2 1  	/* OBJECT in TREE #5 */
#define CMRAICN3 1  	/* OBJECT in TREE #6 */
#define OUTMENUS 17  	/* TREE */
#define DESKMENU 3  	/* OBJECT in TREE #17 */
#define FILEMENU 4  	/* OBJECT in TREE #17 */
#define GPRFMENU 5  	/* OBJECT in TREE #17 */
#define SPRFMENU 6  	/* OBJECT in TREE #17 */
#define PPRFMENU 7  	/* OBJECT in TREE #17 */
#define CPRFMENU 8  	/* OBJECT in TREE #17 */
#define ABOUTITM 11  	/* OBJECT in TREE #17 */
#define NEWITEM 20  	/* OBJECT in TREE #17 */
#define OPENITEM 21  	/* OBJECT in TREE #17 */
#define SAVEITEM 23  	/* OBJECT in TREE #17 */
#define SVASITEM 24  	/* OBJECT in TREE #17 */
#define TOAPPITM 26  	/* OBJECT in TREE #17 */
#define QUITITEM 27  	/* OBJECT in TREE #17 */
#define SHRTITM0 29  	/* OBJECT in TREE #17 */
#define GLOBITM0 31  	/* OBJECT in TREE #17 */
#define SVPFITM0 33  	/* OBJECT in TREE #17 */
#define SCRNITEM 35  	/* OBJECT in TREE #17 */
#define PAGEITEM 37  	/* OBJECT in TREE #17 */
#define PGSZITEM 38  	/* OBJECT in TREE #17 */
#define PTRAYITM 39  	/* OBJECT in TREE #17 */
#define FILERDIR 40  	/* OBJECT in TREE #17 */
#define FILMITEM 42  	/* OBJECT in TREE #17 */
#define COLRITEM 43  	/* OBJECT in TREE #17 */
#define FILEITEM 7  	/* OBJECT in TREE #15 */
#define LPT1ITEM 29		/* FREE STRING */
#define COM1ITEM 30		/* FREE STRING */
#define SPFILNAM 6		/* FREE STRING */
#define BKGNROOT 8  	/* OBJECT in TREE #15 */
#define BKGNDYES 10  	/* OBJECT in TREE #15 */
#define DELEROOT 12  	/* OBJECT in TREE #15 */
#define DELEYES 14  	/* OBJECT in TREE #15 */
#define BKGNDSTR 9  	/* OBJECT in TREE #15 */
#define WIDESIZE 14  	/* OBJECT in TREE #13 */
#define HALFSIZE 9  	/* OBJECT in TREE #13 */
#define HFSZCENT 10		/* FREE STRING */
#define BDSZCENT 14		/* FREE STRING */
#define WDSZCENT 15		/* FREE STRING */
#define HFSZINCH 18		/* FREE STRING */
#define B5SZINCH 25		/* FREE STRING */
#define BDSZINCH 22		/* FREE STRING */
#define WDSZINCH 23		/* FREE STRING */
#define DELESTR 13  	/* OBJECT in TREE #15 */
#define RIGHTBOT 24  	/* OBJECT in TREE #2 */
#define LEFTTOP 16  	/* OBJECT in TREE #2 */
#define POSIROOT 14  	/* OBJECT in TREE #2 */
#define POSIITEM 15  	/* OBJECT in TREE #2 */
#define PRINTER 27		/* FREE STRING */
#define PLOTTER 28		/* FREE STRING */
#define ENDPGNO 11  	/* OBJECT in TREE #8 */
#define STRTPGNO 10  	/* OBJECT in TREE #8 */
#define PSIZICON 1  	/* OBJECT in TREE #13 */
#define PSIZTITL 2  	/* OBJECT in TREE #13 */
#define TRAYTITL 2  	/* OBJECT in TREE #14 */
#define PORTITLE 2  	/* OBJECT in TREE #15 */
#define PRNTITLE 2  	/* OBJECT in TREE #2 */
#define FFSTRING 9  	/* OBJECT in TREE #2 */
#define NOFF 11  	/* OBJECT in TREE #2 */
#define TIMEITEM 12  	/* OBJECT in TREE #1 */
#define SHRTCUT 18  	/* TREE */
#define ALTICON1 4  	/* OBJECT in TREE #18 */
#define ALTICON2 7  	/* OBJECT in TREE #18 */
#define ALTICON3 12  	/* OBJECT in TREE #18 */
#define ALTICON4 15  	/* OBJECT in TREE #18 */
#define KEYAICON 6  	/* OBJECT in TREE #18 */
#define KEYCICON 9  	/* OBJECT in TREE #18 */
#define KEYDICON 14  	/* OBJECT in TREE #18 */
#define KEYSICON 17  	/* OBJECT in TREE #18 */
#define SHRTCANC 19  	/* OBJECT in TREE #18 */
#define SHRTCONT 20  	/* OBJECT in TREE #18 */
#define ESCICON2 7  	/* OBJECT in TREE #1 */
#define SCREEN 26		/* FREE STRING */
#define NOTESTR 20  	/* OBJECT in TREE #15 */
#define CLIPBRD 31		/* FREE STRING */
#define SCRNHELP 16  	/* OBJECT in TREE #1 */
#define GLOBHELP 14  	/* OBJECT in TREE #8 */
#define PTRYHELP 15  	/* OBJECT in TREE #14 */
#define FILMHELP 30  	/* OBJECT in TREE #5 */
#define PRPSHELP 19  	/* OBJECT in TREE #13 */
#define PRFRHELP 21  	/* OBJECT in TREE #15 */
#define SCRNPREH 45  	/* STRING */
#define PRNTHELP 30  	/* OBJECT in TREE #2 */
#define PRNTPREH 46  	/* STRING */
#define HLPNONE 47  	/* STRING */
#define OPENLIST 33		/* FREE STRING */
#define SELFILES 32		/* FREE STRING */
#define SAVELIST 34		/* FREE STRING */
