
/************************************************************************/
/*		Display build in messages				*/
/************************************************************************/

#define	M_TITLE		"DISPLAY"
#define	M_INFO		"File : "
#define M_ERR1		"[3][Fatal Error !|Window not available|for disp.][ Abort ]"
#define	M_ERR2		"[3][Fatal Error !|Can't open selected file|Bye Bye][ Abort ]"
#define	M_RSC		"DISPLAY.RSC"
#define	M_ERR3		"[3] [Fatal Error !|Display.rsc|File Not Found] [Abort]"
#define	M_ITITLE	"  Display"
