

SRCZIP= w10blit.a86   crptdraw.a86  hiccblit.a86  p7pttxt2.a86	u75regs.a86 \
	w10dev.a86    crpttxt1.a86  hicdev.a86	  p8ptdraw.a86	u75_zyxg.a86 \
	w10_drv.a86   crpttxt2.a86  hic_drv.a86   p8pttxt1.a86	u86blit.a86 \
	w10mblit.a86  date.a86	    hicdvsp.a86   p8pttxt2.a86	u86dev.a86 \
	256mmre1.a86  debblit.a86   hicmblit.a86  paptdraw.a86	u86_drv.a86 \
	256mmre2.a86  debdev.a86    hicmmre1.a86  papttxt1.a86	u86mblit.a86 \
	w10pat.a86    deb_drv.a86   hicmmre2.a86  papttxt2.a86	u86regs.a86 \
	w10regs.a86   debmblit.a86  hicpat.a86	  parblit.a86	u86_zyxg.a86 \
	256tdraw.a86  debpat.a86    hicregs.a86   pardev.a86	uniblit.a86 \
	256txt1.a86   debregs.a86   hicspblt.a86  par_drv.a86	unicp.a86 \
	256txt2.a86   debug.a86     hic_zyxg.a86  parmblit.a86	unidev.a86 \
	w10_zyxg.a86  deb_zyxg.a86  hiptdraw.a86  parpat.a86	uni_drv.a86 \
	2bpptxt1.a86  deptdraw.a86  hipttxt1.a86  parregs.a86	unifont.a86 \
	2bpptxt2.a86  depttxt1.a86  hipttxt2.a86  par_zyxg.a86	unimblit.a86 \
	2bptdraw.a86  depttxt2.a86  hirespat.a86  plablit.a86	unipat.a86 \
	w1ptdraw.a86  dummy.a86     hoptdraw.a86  pladev.a86	uniregs.a86 \
	w1pttxt1.a86  e1ptdraw.a86  hopttxt1.a86  pla_drv.a86	uni_zyxg.a86 \
	w1pttxt2.a86  e1pttxt1.a86  hopttxt2.a86  plamblit.a86	uoptdraw.a86 \
	5x14font.a86  e1pttxt2.a86  hrcblit.a86   plapat.a86	uopttxt1.a86 \
	5x7font.a86   e8ptdraw.a86  hrc_drv.a86   plaregs.a86	uopttxt2.a86 \
	700mdvsp.a86  e8pttxt1.a86  hrcmblit.a86  pla_zyxg.a86	v10blit.a86 \
	75ptdraw.a86  e8pttxt2.a86  hrcpat.a86	  plptdraw.a86	v10dev.a86 \
	75pttxt1.a86  egablit.a86   hrc_zyxg.a86  plpttxt1.a86	v10_drv.a86 \
	75pttxt2.a86  egacp.a86     hrptdraw.a86  plpttxt2.a86	v10mblit.a86 \
	86ptdraw.a86  egadev.a86    hrpttxt1.a86  poptdraw.a86	v10pat.a86 \
	86pttxt1.a86  ega_drv.a86   hrpttxt2.a86  popttext.a86	v10regs.a86 \
	86pttxt2.a86  egafont.a86   ibmmdvsp.a86  popttxt1.a86	v10_zyxg.a86 \
	amptdraw.a86  egamblit.a86  imouse.a86	  popttxt2.a86	v1ptdraw.a86 \
	ampttxt1.a86  egammre1.a86  isin.a86	  ps4blit.a86	v1pttxt1.a86 \
	ampttxt2.a86  egammre2.a86  jmptbl.a86	  ps4_drv.a86	v1pttxt2.a86 \
	amsblit.a86   egapat.a86    khmblit.a86   ps4mblit.a86	w6xblit.a86 \
	amsdev.a86    egaregs.a86   khmdev.a86	  ps4pat.a86	w6xdev.a86 \
	ams_drv.a86   ega_zyxg.a86  khm_drv.a86   ps4regs.a86	w6x_drv.a86 \
	amsmblit.a86  eh1blit.a86   khmmblit.a86  ps4_zyxg.a86	w6xmblit.a86 \
	amspat.a86    eh1dev.a86    khmpat.a86	  ps8blit.a86	w6xpat.a86 \
	amsregs.a86   eh1_drv.a86   khmregs.a86   ps8_drv.a86	w6xregs.a86 \
	ams_zyxg.a86  eh1mblit.a86  khm_zyxg.a86  ps8mblit.a86	w6x_zyxg.a86 \
	atptdraw.a86  eh1pat.a86    klfblit.a86   ps8pat.a86	wxptdraw.a86 \
	atpttxt1.a86  eh1regs.a86   klfdev.a86	  ps8regs.a86	wxpttxt1.a86 \
	atpttxt2.a86  eh1_zyxg.a86  klf_drv.a86   ps8_zyxg.a86	wxpttxt2.a86 \
	attblit.a86   eh8blit.a86   klfmblit.a86  psc_drv.a86	v86blit.a86 \
	attdev.a86    eh8dev.a86    klfpat.a86	  ras256.a86	v86dev.a86 \
	att_drv.a86   eh8_drv.a86   klfregs.a86   ras2bpp.a86	v86_drv.a86 \
	attmblit.a86  eh8mblit.a86  klf_zyxg.a86  rastop.a86	v86mblit.a86 \
	attpat.a86    eh8pat.a86    klptdraw.a86  rasvx8.a86	v86pat.a86 \
	attregs.a86   eh8regs.a86   klpttxt1.a86  rcgblit.a86	v86regs.a86 \
	att_zyxg.a86  eh8_zyxg.a86  klpttxt2.a86  rcgdev.a86	v86_zyxg.a86 \
	captdraw.a86  el8blit.a86   kmptdraw.a86  rcg_drv.a86	v8ptdraw.a86 \
	capttxt1.a86  el8dev.a86    kmpttxt1.a86  rcgmblit.a86	v8pttxt1.a86 \
	capttxt2.a86  el8_drv.a86   kmpttxt2.a86  rcgpat.a86	v8pttxt2.a86 \
	catblit.a86   el8mblit.a86  lorespat.a86  rcgregs.a86	\
	catcp.a86     el8pat.a86    mblit.a86	  rcg_zyxg.a86	\
	catdev.a86    el8regs.a86   mcgadev.a86   rcptdraw.a86	\
	cat_drv.a86   el8_zyxg.a86  mcgaregs.a86  rcpttxt1.a86	\
	catfont.a86   elfblit.a86   mcgblit.a86   rcpttxt2.a86	vesadvsp.a86 \
	catmblit.a86  elfdev.a86    mcg_drv.a86   sdw109.inp	\
	catpat.a86    elf_drv.a86   mcgmblit.a86  sdams9.inp	\
	catregs.a86   elfmblit.a86  mcgpat.a86	  sdatt9.inp	\
	cat_zyxg.a86  elfpat.a86    mcg_zyxg.a86  sdcat9.inp	\
	cblit.a86     elfregs.a86   mcptdraw.a86  sdcga9.inp	\
	cgablit.a86   elf_zyxg.a86  mcpttxt1.a86  sdclf9.inp	\
	cgacp.a86     elptdraw.a86  mcpttxt2.a86  sdclr9.inp	\
	cgadev.a86    elpttxt1.a86  mon256.a86	  sddeb9.inp	vgablit.a86 \
	cga_drv.a86   elpttxt2.a86  mon2bpp.a86   sdeh19.inp	vgacols.a86 \
	cgafont.a86   elqtdraw.a86  monmmre1.a86  sdeh89.inp	vgacp.a86 \
	cgamblit.a86  elqttxt1.a86  monmmre2.a86  sdehf9.inp	vgadev.a86 \
	cgapat.a86    elqttxt2.a86  monobj.a86	  sdel89.inp	\
	cgaregs.a86   enddseg.a86   monobjx.a86   sdelf9.inp	vgadrv.a86 \
	cga_zyxg.a86  entry.a86     monobjy.a86   sdgen9.inp	vgafont.a86 \
	cgptdraw.a86  eoptdraw.a86  monout.a86	  sdgsv9.inp	vgamblit.a86 \
	cgpttxt1.a86  eopttxt1.a86  monspblt.a86  sdhic9.inp	vgapat.a86 \
	cgpttxt2.a86  eopttxt2.a86  muentry.a86   sdhrc9.inp	vgaregs.a86 \
	clfblit.a86   externs.a86   opttdraw.a86  sdkhm9.inp	vga_zyxg.a86 \
	clfdev.a86    font.a86	    opttext.a86   sdklf9.inp	vlfblit.a86 \
	clf_drv.a86   genblit.a86   opttxt1.a86   sdp649.inp	vlfdev.a86 \
	clfmblit.a86  gendev.a86    opttxt2.a86   sdp759.inp	vlf_drv.a86 \
	clfpat.a86    gen_drv.a86   p4ptdraw.a86  sdpar9.inp	vlfmblit.a86 \
	clfregs.a86   genmblit.a86  p4pttxt1.a86  sdpla9.inp	vlfpat.a86 \
	clf_zyxg.a86  genpat.a86    p4pttxt2.a86  sdps49.inp	vlfregs.a86 \
	clptdraw.a86  genregs.a86   p640.a86	  sdps89.inp	vlf_zyxg.a86 \
	clpttxt1.a86  gen_zyxg.a86  p64blit.a86   sdpsc9.inp	vlptdraw.a86 \
	clpttxt2.a86  geptdraw.a86  p64dev.a86	  sdpsm9.inp	vlpttxt1.a86 \
	clrblit.a86   gepttxt1.a86  p64_drv.a86   sdrcg9.inp	vlpttxt2.a86 \
	clrdev.a86    gepttxt2.a86  p64mblit.a86  sdu759.inp	voptdraw.a86 \
	clr_drv.a86   gsptdraw.a86  p64pat.a86	  sdu869.inp	vopttxt1.a86 \
	clrmblit.a86  gspttxt1.a86  p64regs.a86   sduni9.inp	vopttxt2.a86 \
	clrpat.a86    gspttxt2.a86  p64_zyxg.a86  sdv109.inp	vx8blit.a86 \
	clrregs.a86   gsvblit.a86   p752.a86	  sdw6x9.inp	wyptdraw.a86 \
	clr_zyxg.a86  gsvdev.a86    p752dev.a86   sdv869.inp	wypttxt1.a86 \
	codepage.a86  gsv_drv.a86   p752regs.a86  		wypttxt2.a86 \
	colmmre1.a86  gsvmblit.a86  p75blit.a86   sdvlf9.inp	wysblit.a86 \
	colmmre2.a86  gsvpat.a86    p75_drv.a86   sdvx89.inp	wys_drv.a86 \
	coptdraw.a86  gsvregs.a86   p75mblit.a86  sdwys9.inp	wysedev.a86 \
	copttext.a86  gsv_zyxg.a86  p75pat.a86	  u75blit.a86	wyseregs.a86 \
	copttxt1.a86  hercdev.a86   p75_zyxg.a86  u75dev.a86	wysmblit.a86 \
	copttxt2.a86  hercregs.a86  p7ptdraw.a86  u75_drv.a86	wyspat.a86 \
	copyrt.a86    hicblit.a86   p7pttxt1.a86  u75mblit.a86	wys_zyxg.a86 \
	w12blit.a86   w12_zyxg.a86  w64_drv.a86   w6pttxt1.a86	w86pat.a86 \
	w12dev.a86    w2ptdraw.a86  w64mblit.a86  w6pttxt2.a86	w86regs.a86 \
	w12_drv.a86   w2pttxt1.a86  w64pat.a86	  w86blit.a86	w86_zyxg.a86 \
	w12mblit.a86  w2pttxt2.a86  w64regs.a86   w86dev.a86	w8ptdraw.a86 \
	w12pat.a86    w64blit.a86   w64_zyxg.a86  w86_drv.a86	w8pttxt1.a86 \
	w12regs.a86   w64dev.a86    w6ptdraw.a86  w86mblit.a86	w8pttxt2.a86 \
	sdw649.inp    sdw869.inp    sdw129.inp    vesapat.a86 \
	fixpal.zip fixpals.zip vidpatch.c \
	readme0.txt readme1.txt readme2.txt readme3.txt readme4.txt \
	copying.txt source.txt Makefile gem.cpi 

VESA_DRIVERS  =sdv869.vga sdv109.vga \
	       sdw649.vga sdw869.vga sdw109.vga sdw129.vga \
	       sdw6x9.vga
CLASS1_DRIVERS=sduni9.vga sdcat9.ega sdhrc9.ega sdu869.vga vidpatch.exe 
CLASS2_DRIVERS=sdpsc9.vga sdpsm9.vga sdehf9.ega sdeh19.ega sdcga9.cga \
	       sdeh89.ega sdelf9.cga sdel89.cga sdrcg9.cga sdclf9.vga \
	       sdclr9.vga sdvlf9.vga sdps89.vga sdps49.vga vidpatch.exe

CLASS3_DRIVERS=sdatt9.ega sdkhm9.ega sdams9.cga sdpla9.cga sdklf9.vga \
	       sdpar9.vga sdu759.vga sdhic9.ega vidpatch.exe 

CLASS4_DRIVERS=sddeb9.ega sdwys9.vga sdgen9.vga sdp649.vga sdp759.ega \
	       sdgsv9.vga


BINZIP0=$(VESA_DRIVERS)   readme0.txt gem.cpi copying.txt 
BINZIP1=$(CLASS1_DRIVERS) readme1.txt gem.cpi copying.txt 
BINZIP2=$(CLASS2_DRIVERS) readme2.txt gem.cpi copying.txt fixpal.zip
BINZIP3=$(CLASS3_DRIVERS) readme3.txt gem.cpi copying.txt fixpal.zip
BINZIP4=$(CLASS4_DRIVERS) readme4.txt gem.cpi copying.txt 

all:	$(CLASS1_DRIVERS) $(CLASS2_DRIVERS) $(CLASS3_DRIVERS) \
	$(CLASS4_DRIVERS) $(VESA_DRIVERS)

#
# Ensure that the linker INP file is big enough - if it isn't you get 
# strange "Syntax error" messages. To be safe add 128 extra spaces to the
# end; LINK86 only reads up to the last multiple of 128 bytes.
#
sdpsc9.vga:	entry.obj jmptbl.obj monobjy.obj  \
		vga_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj psc_drv.obj \
		vgamblit.obj vgablit.obj vopttxt1.obj vopttxt2.obj \
		voptdraw.obj vgapat.obj enddseg.obj
	link86 sdpsc9[i

sdps89.vga:	entry.obj jmptbl.obj monobjy.obj  \
		ps8_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj ps8_drv.obj \
		ps8mblit.obj ps8blit.obj p8pttxt1.obj p8pttxt2.obj \
		p8ptdraw.obj ps8pat.obj enddseg.obj
	link86 sdps89[i

sdps49.vga:	entry.obj jmptbl.obj monobjy.obj  \
		ps4_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj ps4_drv.obj \
		ps4mblit.obj ps4blit.obj p4pttxt1.obj p4pttxt2.obj \
		p4ptdraw.obj ps4pat.obj enddseg.obj
	link86 sdps49[i

sdv869.vga:	entry.obj jmptbl.obj monobjy.obj  \
		v86_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj v86_drv.obj \
		v86mblit.obj v86blit.obj v8pttxt1.obj v8pttxt2.obj \
		v8ptdraw.obj v86pat.obj enddseg.obj
	link86 sdv869[i

sdv109.vga:	entry.obj jmptbl.obj monobjy.obj  \
		v10_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj v10_drv.obj \
		v10mblit.obj v10blit.obj v1pttxt1.obj v1pttxt2.obj \
		v1ptdraw.obj v10pat.obj enddseg.obj
	link86 sdv109[i


sdu869.vga:	entry.obj jmptbl.obj monobjy.obj  \
		u86_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj u86_drv.obj \
		u86mblit.obj u86blit.obj 86pttxt1.obj 86pttxt2.obj \
		86ptdraw.obj v86pat.obj enddseg.obj
	link86 sdu869[i

sdu759.vga:	entry.obj jmptbl.obj monobjy.obj  \
		u75_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj u75_drv.obj \
		u75mblit.obj u75blit.obj 75pttxt1.obj 75pttxt2.obj \
		75ptdraw.obj v86pat.obj enddseg.obj
	link86 sdu759[i

sdw6x9.vga:	entry.obj jmptbl.obj monobjy.obj  \
		w6x_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj w6x_drv.obj \
		w6xmblit.obj w6xblit.obj wxpttxt1.obj wxpttxt2.obj \
		wxptdraw.obj w6xpat.obj enddseg.obj debug.obj
	link86 sdw6x9[i

sdw649.vga:	entry.obj jmptbl.obj monobjy.obj  \
		w64_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj w64_drv.obj \
		w64mblit.obj w64blit.obj w6pttxt1.obj w6pttxt2.obj \
		w6ptdraw.obj w64pat.obj enddseg.obj debug.obj
	link86 sdw649[i

sdw869.vga:	entry.obj jmptbl.obj monobjy.obj  \
		w86_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj w86_drv.obj \
		w86mblit.obj w86blit.obj w8pttxt1.obj w8pttxt2.obj \
		w8ptdraw.obj w86pat.obj enddseg.obj debug.obj
	link86 sdw869[i

sdw109.vga:	entry.obj jmptbl.obj monobjy.obj  \
		w10_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj w10_drv.obj \
		w10mblit.obj w10blit.obj w1pttxt1.obj w1pttxt2.obj \
		w1ptdraw.obj w10pat.obj enddseg.obj debug.obj
	link86 sdw109[i

sdw129.vga:	entry.obj jmptbl.obj monobjy.obj  \
		w12_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj w12_drv.obj \
		w12mblit.obj w12blit.obj w2pttxt1.obj w2pttxt2.obj \
		w2ptdraw.obj w12pat.obj enddseg.obj debug.obj
	link86 sdw129[i


sdpar9.vga:	entry.obj jmptbl.obj monobjy.obj  \
		par_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj par_drv.obj \
		parmblit.obj parblit.obj papttxt1.obj papttxt2.obj \
		paptdraw.obj parpat.obj enddseg.obj debug.obj
	link86 sdpar9[i

sdvlf9.vga:	entry.obj jmptbl.obj monobjy.obj  \
		vlf_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj vlf_drv.obj \
		vlfmblit.obj vlfblit.obj vlpttxt1.obj vlpttxt2.obj \
		vlptdraw.obj vlfpat.obj enddseg.obj debug.obj
	link86 sdvlf9[i

sdpsm9.vga:	entry.obj jmptbl.obj monobjy.obj  \
		mcg_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj mcg_drv.obj \
		mcgmblit.obj mcgblit.obj mcpttxt1.obj mcpttxt2.obj \
		mcptdraw.obj mcgpat.obj enddseg.obj
	link86 sdpsm9[i

sdehf9.ega:	entry.obj jmptbl.obj monobjy.obj  \
		ega_zyxg.obj egacp.obj monout.obj egafont.obj \
		copttext.obj isin.obj dummy.obj ega_drv.obj \
		egamblit.obj egablit.obj eopttxt1.obj eopttxt2.obj \
		eoptdraw.obj egapat.obj enddseg.obj
	link86 sdehf9[i

sdeh89.ega:	entry.obj jmptbl.obj monobjy.obj  \
		eh8_zyxg.obj egacp.obj monout.obj egafont.obj \
		copttext.obj isin.obj dummy.obj eh8_drv.obj \
		eh8mblit.obj eh8blit.obj e8pttxt1.obj e8pttxt2.obj \
		e8ptdraw.obj eh8pat.obj enddseg.obj
	link86 sdeh89[i

sdeh19.ega:	entry.obj jmptbl.obj monobjy.obj  \
		eh1_zyxg.obj egacp.obj monout.obj egafont.obj \
		copttext.obj isin.obj dummy.obj eh1_drv.obj \
		eh1mblit.obj eh1blit.obj e1pttxt1.obj e1pttxt2.obj \
		e1ptdraw.obj eh1pat.obj enddseg.obj
	link86 sdeh19[i

sdelf9.cga:	entry.obj jmptbl.obj monobjy.obj  \
		elf_zyxg.obj cgacp.obj monout.obj cgafont.obj \
		copttext.obj isin.obj dummy.obj elf_drv.obj \
		elfmblit.obj elfblit.obj elpttxt1.obj elpttxt2.obj \
		elptdraw.obj elfpat.obj enddseg.obj
	link86 sdelf9[i

sdel89.cga:	entry.obj jmptbl.obj monobjy.obj  \
		el8_zyxg.obj cgacp.obj monout.obj cgafont.obj \
		copttext.obj isin.obj dummy.obj el8_drv.obj \
		el8mblit.obj el8blit.obj elqttxt1.obj elqttxt2.obj \
		elqtdraw.obj el8pat.obj enddseg.obj
	link86 sdel89[i

sdams9.cga:	entry.obj jmptbl.obj monobjy.obj  \
		ams_zyxg.obj cgacp.obj monout.obj cgafont.obj \
		copttext.obj isin.obj dummy.obj ams_drv.obj \
		amsmblit.obj amsblit.obj ampttxt1.obj ampttxt2.obj \
		amptdraw.obj amspat.obj enddseg.obj
	link86 sdams9[i

sdclf9.vga:	entry.obj jmptbl.obj monobjy.obj  \
		clf_zyxg.obj monout.obj 5x7font.obj \
		copttext.obj isin.obj dummy.obj clf_drv.obj \
		clfmblit.obj clfblit.obj clpttxt1.obj clpttxt2.obj \
		clptdraw.obj clfpat.obj enddseg.obj # 5x7cp.obj
	link86 sdclf9[i

sdclr9.vga:	entry.obj jmptbl.obj monobjy.obj  \
		clr_zyxg.obj monout.obj 5x7font.obj \
		copttext.obj isin.obj dummy.obj clr_drv.obj \
		clrmblit.obj clrblit.obj crpttxt1.obj crpttxt2.obj \
		crptdraw.obj clrpat.obj enddseg.obj # 5x7cp.obj
	link86 sdclr9[i

sdrcg9.cga:	entry.obj jmptbl.obj monobjy.obj  \
		rcg_zyxg.obj cgacp.obj monout.obj cgafont.obj \
		copttext.obj isin.obj dummy.obj rcg_drv.obj \
		rcgmblit.obj rcgblit.obj rcpttxt1.obj rcpttxt2.obj \
		rcptdraw.obj rcgpat.obj enddseg.obj
	link86 sdrcg9[i

sdcga9.cga:	entry.obj jmptbl.obj monobjy.obj  \
		cga_zyxg.obj cgacp.obj monout.obj cgafont.obj \
		copttext.obj isin.obj dummy.obj cga_drv.obj \
		cgamblit.obj cgablit.obj cgpttxt1.obj cgpttxt2.obj \
		cgptdraw.obj cgapat.obj enddseg.obj
	link86 sdcga9[i

sdpla9.cga:	entry.obj jmptbl.obj monobjy.obj  \
		pla_zyxg.obj cgacp.obj monout.obj cgafont.obj \
		copttext.obj isin.obj dummy.obj pla_drv.obj \
		plamblit.obj plablit.obj plpttxt1.obj plpttxt2.obj \
		plptdraw.obj plapat.obj enddseg.obj
	link86 sdpla9[i


sdcat9.ega:	entry.obj jmptbl.obj monobjy.obj  \
		cat_zyxg.obj catcp.obj monout.obj catfont.obj \
		copttext.obj isin.obj dummy.obj cat_drv.obj \
		catmblit.obj catblit.obj capttxt1.obj capttxt2.obj \
		captdraw.obj catpat.obj enddseg.obj
	link86 sdcat9[i


sdatt9.ega:	entry.obj jmptbl.obj monobjy.obj  \
		att_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj att_drv.obj \
		attmblit.obj attblit.obj atpttxt1.obj atpttxt2.obj \
		atptdraw.obj attpat.obj enddseg.obj
	link86 sdatt9[i

sddeb9.ega:	entry.obj jmptbl.obj monobjy.obj  \
		deb_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj deb_drv.obj \
		debmblit.obj debblit.obj depttxt1.obj depttxt2.obj \
		deptdraw.obj debpat.obj enddseg.obj
	link86 sddeb9[i

sdkhm9.ega:	entry.obj jmptbl.obj monobjy.obj  \
		khm_zyxg.obj egacp.obj monout.obj egafont.obj \
		copttext.obj isin.obj dummy.obj khm_drv.obj \
		khmmblit.obj khmblit.obj kmpttxt1.obj kmpttxt2.obj \
		kmptdraw.obj khmpat.obj enddseg.obj
	link86 sdkhm9[i


sdklf9.vga:	entry.obj jmptbl.obj monobjx.obj  \
		klf_zyxg.obj egacp.obj monout.obj 5x14font.obj \
		copttext.obj isin.obj dummy.obj klf_drv.obj \
		klfmblit.obj klfblit.obj klpttxt1.obj klpttxt2.obj \
		klptdraw.obj klfpat.obj enddseg.obj # 5x14cp.obj
	link86 sdklf9[i



sdhic9.ega:	entry.obj jmptbl.obj monobjy.obj  \
		hic_zyxg.obj egacp.obj monout.obj egafont.obj \
		copttext.obj isin.obj dummy.obj hic_drv.obj \
		hicmblit.obj hicblit.obj hipttxt1.obj hipttxt2.obj \
		hiptdraw.obj hicpat.obj enddseg.obj
	link86 sdhic9[i

sdhrc9.ega:	entry.obj jmptbl.obj monobjy.obj  \
		hrc_zyxg.obj egacp.obj monout.obj egafont.obj \
		copttext.obj isin.obj dummy.obj hrc_drv.obj \
		hrcmblit.obj hrcblit.obj hrpttxt1.obj hrpttxt2.obj \
		hrptdraw.obj hrcpat.obj enddseg.obj
	link86 sdhrc9[i

sdwys9.vga:	entry.obj jmptbl.obj monobjy.obj  \
		wys_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj wys_drv.obj \
		wysmblit.obj wysblit.obj wypttxt1.obj wypttxt2.obj \
		wyptdraw.obj wyspat.obj enddseg.obj
	link86 sdwys9[i

sdgen9.vga:	entry.obj jmptbl.obj monobjy.obj  \
		gen_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj gen_drv.obj \
		genmblit.obj genblit.obj gepttxt1.obj gepttxt2.obj \
		geptdraw.obj genpat.obj enddseg.obj
	link86 sdgen9[i

sdgsv9.vga:	entry.obj jmptbl.obj monobjy.obj  \
		gsv_zyxg.obj vgacp.obj monout.obj vgafont.obj \
		copttext.obj isin.obj dummy.obj gsv_drv.obj \
		gsvmblit.obj gsvblit.obj gspttxt1.obj gspttxt2.obj \
		gsptdraw.obj gsvpat.obj enddseg.obj
	link86 sdgsv9[i


sdp649.vga:	entry.obj jmptbl.obj monobjy.obj  \
		p64_zyxg.obj monout.obj vgacp.obj vgafont.obj \
		popttext.obj isin.obj dummy.obj p64_drv.obj \
		p64mblit.obj p64blit.obj popttxt1.obj popttxt2.obj \
		poptdraw.obj p64pat.obj enddseg.obj p640.obj
	link86 sdp649[i

sdp759.ega:	entry.obj jmptbl.obj monobjy.obj  \
		p75_zyxg.obj monout.obj vgacp.obj vgafont.obj \
		popttext.obj isin.obj dummy.obj p75_drv.obj \
		p75mblit.obj p75blit.obj p7pttxt1.obj p7pttxt2.obj \
		p7ptdraw.obj p75pat.obj enddseg.obj p752.obj
	link86 sdp759[i


sduni9.vga:	entry.obj jmptbl.obj monobjy.obj  \
		uni_zyxg.obj unicp.obj monout.obj unifont.obj \
		copttext.obj isin.obj dummy.obj uni_drv.obj \
		unimblit.obj uniblit.obj uopttxt1.obj uopttxt2.obj \
		uoptdraw.obj unipat.obj enddseg.obj
	link86 sduni9[i


%.obj:	%.a86 externs.a86
	rasm86 $< $$pzsz

pla_drv.obj:	pla_drv.a86 plaregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		monmmre1.a86 monmmre2.a86 pladev.a86 date.a86 copyrt.a86
ams_drv.obj:	ams_drv.a86 amsregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		monmmre1.a86 monmmre2.a86 amsdev.a86 date.a86 copyrt.a86
clf_drv.obj:	clf_drv.a86 clfregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		colmmre1.a86 colmmre2.a86 clfdev.a86 date.a86 copyrt.a86
clr_drv.obj:	clr_drv.a86 clrregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		colmmre1.a86 colmmre2.a86 clrdev.a86 date.a86 copyrt.a86
rcg_drv.obj:	rcg_drv.a86 rcgregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		monmmre1.a86 monmmre2.a86 rcgdev.a86 date.a86 copyrt.a86
cga_drv.obj:	cga_drv.a86 cgaregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		monmmre1.a86 monmmre2.a86 cgadev.a86 date.a86 copyrt.a86
cat_drv.obj:	cat_drv.a86 catregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		monmmre1.a86 monmmre2.a86 catdev.a86 date.a86 copyrt.a86
att_drv.obj:	att_drv.a86 attregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		monmmre1.a86 monmmre2.a86 attdev.a86 date.a86 copyrt.a86
deb_drv.obj:	deb_drv.a86 debregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		monmmre1.a86 monmmre2.a86 debdev.a86 date.a86 copyrt.a86
gen_drv.obj:	gen_drv.a86 genregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		monmmre1.a86 monmmre2.a86 gendev.a86 date.a86 copyrt.a86
gsv_drv.obj:	gsv_drv.a86 gsvregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 gsvdev.a86 date.a86 copyrt.a86
hic_drv.obj:	hic_drv.a86 hercregs.a86 externs.a86 hicdvsp.a86 imouse.a86 \
		hicmmre1.a86 hicmmre2.a86 hicdev.a86 date.a86 copyrt.a86
hrc_drv.obj:	hrc_drv.a86 hercregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		monmmre1.a86 monmmre2.a86 hercdev.a86 date.a86 copyrt.a86
khm_drv.obj:	khm_drv.a86 khmregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 khmdev.a86 date.a86 copyrt.a86
klf_drv.obj:	klf_drv.a86 klfregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 klfdev.a86 date.a86 copyrt.a86
wys_drv.obj:	wys_drv.a86 hercregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		monmmre1.a86 monmmre2.a86 hercdev.a86 date.a86 copyrt.a86
ega_drv.obj:	ega_drv.a86 egaregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 egadev.a86 date.a86 copyrt.a86
eh1_drv.obj:	eh1_drv.a86 eh1regs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 eh1dev.a86 date.a86 copyrt.a86
eh8_drv.obj:	eh8_drv.a86 eh8regs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 eh8dev.a86 date.a86 copyrt.a86
elf_drv.obj:	elf_drv.a86 elfregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 elfdev.a86 date.a86 copyrt.a86
el8_drv.obj:	el8_drv.a86 el8regs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 el8dev.a86 date.a86 copyrt.a86
psc_drv.obj:	psc_drv.a86 vgaregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 vgadev.a86 date.a86 copyrt.a86 \
		vgadrv.a86 vgacols.a86
ps8_drv.obj:	ps8_drv.a86 vgaregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 vgadev.a86 date.a86 copyrt.a86 \
		vgadrv.a86 vgacols.a86
ps4_drv.obj:	ps4_drv.a86 vgaregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 vgadev.a86 date.a86 copyrt.a86 \
		vgadrv.a86 vgacols.a86
uni_drv.obj:	uni_drv.a86 uniregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 unidev.a86 date.a86 copyrt.a86
mcg_drv.obj:	mcg_drv.a86 mcgaregs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		monmmre1.a86 monmmre2.a86 mcgadev.a86 date.a86 copyrt.a86
v86_drv.obj:	v86_drv.a86 v86regs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 v86dev.a86 date.a86 copyrt.a86 \
		vgacols.a86
u86_drv.obj:	u86_drv.a86 u86regs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 u86dev.a86 date.a86 copyrt.a86 \
		vgacols.a86
u75_drv.obj:	u75_drv.a86 u75regs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 u75dev.a86 date.a86 copyrt.a86 \
		vgacols.a86
vlf_drv.obj:	vlf_drv.a86 vlfregs.a86 externs.a86 vesadvsp.a86 imouse.a86 \
		256mmre1.a86 256mmre2.a86 vlfdev.a86 date.a86 copyrt.a86
w6x_drv.obj:	w6x_drv.a86 w6xregs.a86 externs.a86 vesadvsp.a86 imouse.a86 \
		256mmre1.a86 256mmre2.a86 w6xdev.a86 date.a86 copyrt.a86
w64_drv.obj:	w64_drv.a86 w64regs.a86 externs.a86 vesadvsp.a86 imouse.a86 \
		256mmre1.a86 256mmre2.a86 w64dev.a86 date.a86 copyrt.a86
w86_drv.obj:	w86_drv.a86 w86regs.a86 externs.a86 vesadvsp.a86 imouse.a86 \
		256mmre1.a86 256mmre2.a86 w86dev.a86 date.a86 copyrt.a86
w10_drv.obj:	w10_drv.a86 w10regs.a86 externs.a86 vesadvsp.a86 imouse.a86 \
		256mmre1.a86 256mmre2.a86 w10dev.a86 date.a86 copyrt.a86
w12_drv.obj:	w12_drv.a86 w12regs.a86 externs.a86 vesadvsp.a86 imouse.a86 \
		256mmre1.a86 256mmre2.a86 w12dev.a86 date.a86 copyrt.a86
par_drv.obj:	par_drv.a86 parregs.a86 externs.a86 vesadvsp.a86 imouse.a86 \
		256mmre1.a86 256mmre2.a86 pardev.a86 date.a86 copyrt.a86
p64_drv.obj:	p64_drv.a86 p64regs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 p64dev.a86 date.a86 copyrt.a86
p75_drv.obj:	p75_drv.a86 p752regs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 p752dev.a86 date.a86 copyrt.a86
v10_drv.obj:	v10_drv.a86 v10regs.a86 externs.a86 ibmmdvsp.a86 imouse.a86 \
		egammre1.a86 egammre2.a86 v10dev.a86 date.a86 copyrt.a86 \
		vgacols.a86

monobjx.obj:	monobjx.a86 monobj.a86 externs.a86
monobjy.obj:	monobjy.a86 monobj.a86 externs.a86

vgamblit.obj:	vgamblit.a86 mblit.a86
vgablit.obj:	vgablit.a86 cblit.a86
vopttxt1.obj:	vopttxt1.a86 copttxt1.a86
vopttxt2.obj:	vopttxt2.a86 copttxt2.a86
voptdraw.obj:	voptdraw.a86 coptdraw.a86
vgapat.obj:	vgapat.a86 hirespat.a86
vgacp.obj:	vgacp.a86 codepage.a86
vgafont.obj:	vgafont.a86 font.a86

egamblit.obj:	egamblit.a86 mblit.a86
egablit.obj:	egablit.a86 cblit.a86
eopttxt1.obj:	eopttxt1.a86 copttxt1.a86
eopttxt2.obj:	eopttxt2.a86 copttxt2.a86
eoptdraw.obj:	eoptdraw.a86 coptdraw.a86
egapat.obj:	egapat.a86 hirespat.a86
egacp.obj:	egacp.a86 codepage.a86
egafont.obj:	egafont.a86 font.a86

eh8mblit.obj:	eh8mblit.a86 mblit.a86
eh8blit.obj:	eh8blit.a86 cblit.a86
e8pttxt1.obj:	e8pttxt1.a86 copttxt1.a86
e8pttxt2.obj:	e8pttxt2.a86 copttxt2.a86
e8ptdraw.obj:	e8ptdraw.a86 coptdraw.a86
eh8pat.obj:	eh8pat.a86 hirespat.a86

gsvmblit.obj:	gsvmblit.a86 mblit.a86
gsvblit.obj:	gsvblit.a86 cblit.a86
gspttxt1.obj:	gspttxt1.a86 copttxt1.a86
gspttxt2.obj:	gspttxt2.a86 copttxt2.a86
gsptdraw.obj:	gsptdraw.a86 coptdraw.a86
gsvpat.obj:	gsvpat.a86 hirespat.a86

eh1mblit.obj:	eh1mblit.a86 mblit.a86
eh1blit.obj:	eh1blit.a86 cblit.a86
e1pttxt1.obj:	e1pttxt1.a86 copttxt1.a86
e1pttxt2.obj:	e1pttxt2.a86 copttxt2.a86
e1ptdraw.obj:	e1ptdraw.a86 coptdraw.a86
eh1pat.obj:	eh1pat.a86 hirespat.a86

elfmblit.obj:	elfmblit.a86 mblit.a86
elfblit.obj:	elfblit.a86 cblit.a86
elpttxt1.obj:	elpttxt1.a86 copttxt1.a86
elpttxt2.obj:	elpttxt2.a86 copttxt2.a86
elptdraw.obj:	elptdraw.a86 coptdraw.a86
elfpat.obj:	elfpat.a86 lorespat.a86

el8mblit.obj:	el8mblit.a86 mblit.a86
el8blit.obj:	el8blit.a86 cblit.a86
elqttxt1.obj:	elqttxt1.a86 copttxt1.a86
elqttxt2.obj:	elqttxt2.a86 copttxt2.a86
elqtdraw.obj:	elqtdraw.a86 coptdraw.a86
el8pat.obj:	el8pat.a86 lorespat.a86

khmmblit.obj:	khmmblit.a86 mblit.a86
khmblit.obj:	khmblit.a86 cblit.a86
kmpttxt1.obj:	kmpttxt1.a86 copttxt1.a86
kmpttxt2.obj:	kmpttxt2.a86 copttxt2.a86
kmptdraw.obj:	kmptdraw.a86 coptdraw.a86
khmpat.obj:	khmpat.a86 hirespat.a86

klfmblit.obj:	klfmblit.a86 mblit.a86
klfblit.obj:	klfblit.a86 cblit.a86
klpttxt1.obj:	klpttxt1.a86 copttxt1.a86
klpttxt2.obj:	klpttxt2.a86 copttxt2.a86
klptdraw.obj:	klptdraw.a86 coptdraw.a86
klfpat.obj:	klfpat.a86 hirespat.a86

clfmblit.obj:	clfmblit.a86 mon2bpp.a86
clfblit.obj:	clfblit.a86 ras2bpp.a86
clpttxt1.obj:	clpttxt1.a86 2bpptxt1.a86
clpttxt2.obj:	clpttxt2.a86 2bpptxt2.a86
clptdraw.obj:	clptdraw.a86 2bptdraw.a86
clfpat.obj:	clfpat.a86 lorespat.a86

clrmblit.obj:	clrmblit.a86 mon2bpp.a86
clrblit.obj:	clrblit.a86 ras2bpp.a86
crpttxt1.obj:	crpttxt1.a86 2bpptxt1.a86
crpttxt2.obj:	crpttxt2.a86 2bpptxt2.a86
crptdraw.obj:	crptdraw.a86 2bptdraw.a86
clrpat.obj:	clrpat.a86 lorespat.a86

plamblit.obj:	plamblit.a86 monspblt.a86
plablit.obj:	plablit.a86 rastop.a86
plpttxt1.obj:	plpttxt1.a86 opttxt1.a86
plpttxt2.obj:	plpttxt2.a86 opttxt2.a86
plptdraw.obj:	plptdraw.a86 opttdraw.a86
plapat.obj:	plapat.a86 lorespat.a86

rcgmblit.obj:	rcgmblit.a86 monspblt.a86
rcgblit.obj:	rcgblit.a86 rastop.a86
rcpttxt1.obj:	rcpttxt1.a86 opttxt1.a86
rcpttxt2.obj:	rcpttxt2.a86 opttxt2.a86
rcptdraw.obj:	rcptdraw.a86 opttdraw.a86
rcgpat.obj:	rcgpat.a86 lorespat.a86

amsmblit.obj:	amsmblit.a86 monspblt.a86
amsblit.obj:	amsblit.a86 rastop.a86
ampttxt1.obj:	ampttxt1.a86 opttxt1.a86
ampttxt2.obj:	ampttxt2.a86 opttxt2.a86
amptdraw.obj:	amptdraw.a86 opttdraw.a86
amspat.obj:	amspat.a86 lorespat.a86

cgamblit.obj:	cgamblit.a86 monspblt.a86
cgablit.obj:	cgablit.a86 rastop.a86
cgpttxt1.obj:	cgpttxt1.a86 opttxt1.a86
cgpttxt2.obj:	cgpttxt2.a86 opttxt2.a86
cgptdraw.obj:	cgptdraw.a86 opttdraw.a86
cgapat.obj:	cgapat.a86 lorespat.a86
cgacp.obj:	cgacp.a86 codepage.a86
cgafont.obj:	cgafont.a86 font.a86

catmblit.obj:	catmblit.a86 monspblt.a86
catblit.obj:	catblit.a86 rastop.a86
capttxt1.obj:	capttxt1.a86 opttxt1.a86
capttxt2.obj:	capttxt2.a86 opttxt2.a86
captdraw.obj:	captdraw.a86 opttdraw.a86
catpat.obj:	catpat.a86 lorespat.a86
catcp.obj:	catcp.a86 codepage.a86
catfont.obj:	catfont.a86 font.a86

depmblit.obj:	depmblit.a86 monspblt.a86
depblit.obj:	depblit.a86 rastop.a86
depttxt1.obj:	depttxt1.a86 opttxt1.a86
depttxt2.obj:	depttxt2.a86 opttxt2.a86
deptdraw.obj:	deptdraw.a86 opttdraw.a86
deppat.obj:	deppat.a86 lorespat.a86

attmblit.obj:	attmblit.a86 monspblt.a86
attblit.obj:	attblit.a86 rastop.a86
atpttxt1.obj:	atpttxt1.a86 opttxt1.a86
atpttxt2.obj:	atpttxt2.a86 opttxt2.a86
atptdraw.obj:	atptdraw.a86 opttdraw.a86
attpat.obj:	attpat.a86 lorespat.a86

hicmblit.obj:	hicmblit.a86 hicspblt.a86 #monspblt.a86
hicblit.obj:	hicblit.a86 hiccblit.a86 #rastop.a86
hipttxt1.obj:	hipttxt1.a86 hopttxt1.a86
hipttxt2.obj:	hipttxt2.a86 hopttxt2.a86
hiptdraw.obj:	hiptdraw.a86 hoptdraw.a86
hicpat.obj:	hicpat.a86 hirespat.a86

hrcmblit.obj:	hrcmblit.a86 monspblt.a86
hrcblit.obj:	hrcblit.a86 rastop.a86
hrpttxt1.obj:	hrpttxt1.a86 opttxt1.a86
hrpttxt2.obj:	hrpttxt2.a86 opttxt2.a86
hrptdraw.obj:	hrptdraw.a86 opttdraw.a86
hrcpat.obj:	hrcpat.a86 hirespat.a86

wysmblit.obj:	wysmblit.a86 monspblt.a86
wysblit.obj:	wysblit.a86 rastop.a86
wypttxt1.obj:	wypttxt1.a86 opttxt1.a86
wypttxt2.obj:	wypttxt2.a86 opttxt2.a86
wyptdraw.obj:	wyptdraw.a86 opttdraw.a86
wyspat.obj:	wyspat.a86 hirespat.a86

mcgmblit.obj:	mcgmblit.a86 monspblt.a86
mcgblit.obj:	mcgblit.a86 rastop.a86
mcpttxt1.obj:	mcpttxt1.a86 opttxt1.a86
mcpttxt2.obj:	mcpttxt2.a86 opttxt2.a86
mcptdraw.obj:	mcptdraw.a86 opttdraw.a86
mcgpat.obj:	mcgpat.a86 hirespat.a86

genmblit.obj:	genmblit.a86 monspblt.a86
genblit.obj:	genblit.a86 rastop.a86
gepttxt1.obj:	gepttxt1.a86 opttxt1.a86
gepttxt2.obj:	gepttxt2.a86 opttxt2.a86
geptdraw.obj:	geptdraw.a86 opttdraw.a86
genpat.obj:	genpat.a86 hirespat.a86

p64mblit.obj:	p64mblit.a86 monspblt.a86
p64blit.obj:	p64blit.a86 rastop.a86
popttxt1.obj:	popttxt1.a86 opttxt1.a86
popttxt2.obj:	popttxt2.a86 opttxt2.a86
poptdraw.obj:	poptdraw.a86 opttdraw.a86
p64pat.obj:	p64pat.a86 hirespat.a86

p75mblit.obj:	p75mblit.a86 monspblt.a86
p75blit.obj:	p75blit.a86 rastop.a86
p7pttxt1.obj:	p7pttxt1.a86 opttxt1.a86
p7pttxt2.obj:	p7pttxt2.a86 opttxt2.a86
p7ptdraw.obj:	p7ptdraw.a86 opttdraw.a86
p75pat.obj:	p75pat.a86 hirespat.a86

unimblit.obj:	unimblit.a86 mblit.a86
uniblit.obj:	uniblit.a86 cblit.a86
unpttxt1.obj:	unpttxt1.a86 copttxt1.a86
unpttxt2.obj:	unpttxt2.a86 copttxt2.a86
unptdraw.obj:	unptdraw.a86 coptdraw.a86
unipat.obj:	unipat.a86 hirespat.a86

v86mblit.obj:	v86mblit.a86 mblit.a86
v86blit.obj:	v86blit.a86 cblit.a86
v8pttxt1.obj:	v8pttxt1.a86 copttxt1.a86
v8pttxt2.obj:	v8pttxt2.a86 copttxt2.a86
v8ptdraw.obj:	v8ptdraw.a86 coptdraw.a86
v86pat.obj:	v86pat.a86 hirespat.a86

u86mblit.obj:	u86mblit.a86 mblit.a86
u86blit.obj:	u86blit.a86 cblit.a86
86pttxt1.obj:	86pttxt1.a86 copttxt1.a86
86pttxt2.obj:	86pttxt2.a86 copttxt2.a86
86ptdraw.obj:	86ptdraw.a86 coptdraw.a86

u75mblit.obj:	u75mblit.a86 mblit.a86
u75blit.obj:	u75blit.a86 cblit.a86
75pttxt1.obj:	75pttxt1.a86 copttxt1.a86
75pttxt2.obj:	75pttxt2.a86 copttxt2.a86
75ptdraw.obj:	75ptdraw.a86 coptdraw.a86

parmblit.obj:	parmblit.a86 mon256.a86
parblit.obj:	parblit.a86 rasvx8.a86
papttxt1.obj:	papttxt1.a86 256txt1.a86
papttxt2.obj:	papttxt2.a86 256txt2.a86
paptdraw.obj:	paptdraw.a86 256tdraw.a86
parpat.obj:	parpat.a86 vesapat.a86

w64mblit.obj:	w64mblit.a86 mon256.a86
w64blit.obj:	w64blit.a86 rasvx8.a86
w6pttxt1.obj:	w6pttxt1.a86 256txt1.a86
w6pttxt2.obj:	w6pttxt2.a86 256txt2.a86
w6ptdraw.obj:	w6ptdraw.a86 256tdraw.a86
w64pat.obj:	w64pat.a86 vesapat.a86

w86mblit.obj:	w86mblit.a86 mon256.a86
w86blit.obj:	w86blit.a86 rasvx8.a86
w8pttxt1.obj:	w8pttxt1.a86 256txt1.a86
w8pttxt2.obj:	w8pttxt2.a86 256txt2.a86
w8ptdraw.obj:	w8ptdraw.a86 256tdraw.a86
w86pat.obj:	w86pat.a86 vesapat.a86

w10mblit.obj:	w10mblit.a86 mon256.a86
w10blit.obj:	w10blit.a86 rasvx8.a86
w1pttxt1.obj:	w1pttxt1.a86 256txt1.a86
w1pttxt2.obj:	w1pttxt2.a86 256txt2.a86
w1ptdraw.obj:	w1ptdraw.a86 256tdraw.a86
w10pat.obj:	w10pat.a86 vesapat.a86

w12mblit.obj:	w12mblit.a86 mon256.a86
w12blit.obj:	w12blit.a86 rasvx8.a86
w2pttxt1.obj:	w2pttxt1.a86 256txt1.a86
w2pttxt2.obj:	w2pttxt2.a86 256txt2.a86
w2ptdraw.obj:	w2ptdraw.a86 256tdraw.a86
w12pat.obj:	w12pat.a86 vesapat.a86

w6xmblit.obj:	w6xmblit.a86 mon256.a86
w6xblit.obj:	w6xblit.a86 rasvx8.a86
wxpttxt1.obj:	wxpttxt1.a86 256txt1.a86
wxpttxt2.obj:	wxpttxt2.a86 256txt2.a86
wxptdraw.obj:	wxptdraw.a86 256tdraw.a86
w6xpat.obj:	w6xpat.a86 vesapat.a86

vlfmblit.obj:	vlfmblit.a86 mon256.a86
vlfblit.obj:	vlfblit.a86 rasvx8.a86
vlpttxt1.obj:	vlpttxt1.a86 256txt1.a86
vlpttxt2.obj:	vlpttxt2.a86 256txt2.a86
vlptdraw.obj:	vlptdraw.a86 256tdraw.a86
vlfpat.obj:	vlfpat.a86 vesapat.a86

v10mblit.obj:	v10mblit.a86 mblit.a86
v10blit.obj:	v10blit.a86 cblit.a86
v1pttxt1.obj:	v1pttxt1.a86 copttxt1.a86
v1pttxt2.obj:	v1pttxt2.a86 copttxt2.a86
v1ptdraw.obj:	v1ptdraw.a86 coptdraw.a86
v10pat.obj:	v10pat.a86 hirespat.a86

ps8mblit.obj:	ps8mblit.a86 mblit.a86
ps8blit.obj:	ps8blit.a86 cblit.a86
p8pttxt1.obj:	p8pttxt1.a86 copttxt1.a86
p8pttxt2.obj:	p8pttxt2.a86 copttxt2.a86
p8ptdraw.obj:	p8ptdraw.a86 coptdraw.a86
ps8pat.obj:	ps8pat.a86 hirespat.a86

ps4mblit.obj:	ps4mblit.a86 mblit.a86
ps4blit.obj:	ps4blit.a86 cblit.a86
p8pttxt1.obj:	p8pttxt1.a86 copttxt1.a86
p8pttxt2.obj:	p8pttxt2.a86 copttxt2.a86
p8ptdraw.obj:	p8ptdraw.a86 coptdraw.a86
ps4pat.obj:	ps4pat.a86 hirespat.a86


copttext.obj:	copttext.a86 opttext.a86
popttext.obj:	popttext.a86 opttext.a86

vidpatch.exe:	vidpatch.c
	pacc $<

zip:	$(SRCZIP) $(BINZIP)
	zip fgdrvs.zip $(SRCZIP)
	zip fgdrvb0.zip $(BINZIP0)
	zip fgdrvb1.zip $(BINZIP1)
	zip fgdrvb2.zip $(BINZIP2)
	zip fgdrvb3.zip $(BINZIP3)
	zip fgdrvb4.zip $(BINZIP4)
