pragma CGROUP("PGROUP");
pragma literals("DATA");
pragma Memory_model(Compact);
pragma On(Int_Function_Warnings);
pragma On(Parm_Warnings);
pragma Off(Public_Var_Warnings);
pragma On(Pointers_Compatible_With_Ints);
pragma On(Pointers_Compatible);
pragma On(Optimize_For_Space);
pragma On(Return_32_In_BX_AX);
pragma Code("PROG");
pragma Cclass("PROG");
pragma Static_Segment("DATA");
pragma On(Read_Only_Strings);
pragma Global_Aliasing_Convention("%C%r:1:8");
pragma Ipath("E:/;C:/OBJ/COMPACT/;C:/OBJ/COMPACT/LIB/");

