#define OUTMENUS 0  	/* TREE */
#define OUTINFO 1  	/* TREE */
#define SCROPTS 2  	/* TREE */
#define PRNTOPTS 3  	/* TREE */
#define PRTCNT 4  	/* TREE */
#define FILEMISS 5  	/* TREE */
#define FILMOPT 6  	/* TREE */
#define CAMCOLR 7  	/* TREE */
#define FRSTRING 8  	/* TREE */
#define PLOTOPTS 9  	/* TREE */
#define STRTTREE 10  	/* TREE */
#define PAGEOPTS 11  	/* TREE */
#define FILETREE 12  	/* TREE */
#define CNTLTREE 13  	/* TREE */
#define SHRTCUT2 14  	/* TREE */
#define SHRTCUT1 15  	/* TREE */
#define HRESICNS 16  	/* TREE */
#define XYZZZZZ 0  	/* OBJECT in TREE #0 */
#define DESKMENU 3  	/* OBJECT in TREE #0 */
#define FILEMENU 4  	/* OBJECT in TREE #0 */
#define OPTSMENU 5  	/* OBJECT in TREE #0 */
#define ABOUITEM 8  	/* OBJECT in TREE #0 */
#define NEWITEM 17  	/* OBJECT in TREE #0 */
#define OPENITEM 18  	/* OBJECT in TREE #0 */
#define SAVEITEM 20  	/* OBJECT in TREE #0 */
#define SVASITEM 21  	/* OBJECT in TREE #0 */
#define TAPPITEM 23  	/* OBJECT in TREE #0 */
#define QUITITEM 24  	/* OBJECT in TREE #0 */
#define MKDFITEM 26  	/* OBJECT in TREE #0 */
#define PAGEITEM 28  	/* OBJECT in TREE #0 */
#define PRNTITEM 29  	/* OBJECT in TREE #0 */
#define SCRNITEM 30  	/* OBJECT in TREE #0 */
#define PLTRITEM 31  	/* OBJECT in TREE #0 */
#define CMFMITEM 32  	/* OBJECT in TREE #0 */
#define CMCLITEM 33  	/* OBJECT in TREE #0 */
#define SHRTCUTS 35  	/* OBJECT in TREE #0 */
#define LOGOICON 1  	/* OBJECT in TREE #1 */
#define GEMICON 2  	/* OBJECT in TREE #1 */
#define VERSNUM 3  	/* OBJECT in TREE #1 */
#define OKINFO 11  	/* OBJECT in TREE #1 */
#define SCRNICN2 1  	/* OBJECT in TREE #2 */
#define WAITROOT 4  	/* OBJECT in TREE #2 */
#define XYZZZZZZ 5  	/* OBJECT in TREE #2 */
#define WAITKEY 6  	/* OBJECT in TREE #2 */
#define WAIT2 7  	/* OBJECT in TREE #2 */
#define WAIT5 8  	/* OBJECT in TREE #2 */
#define WAIT10 9  	/* OBJECT in TREE #2 */
#define WAIT20 10  	/* OBJECT in TREE #2 */
#define CYCLROOT 11  	/* OBJECT in TREE #2 */
#define NOCYCLE 13  	/* OBJECT in TREE #2 */
#define YESCYCLE 14  	/* OBJECT in TREE #2 */
#define OKSCRN 15  	/* OBJECT in TREE #2 */
#define CANSCRN 16  	/* OBJECT in TREE #2 */
#define PRNTICN2 1  	/* OBJECT in TREE #3 */
#define PRSCROOT 3  	/* OBJECT in TREE #3 */
#define PRNTFS 5  	/* OBJECT in TREE #3 */
#define IFFROOT 7  	/* OBJECT in TREE #3 */
#define YESIFF 9  	/* OBJECT in TREE #3 */
#define FFFROOT 11  	/* OBJECT in TREE #3 */
#define YESFFF 13  	/* OBJECT in TREE #3 */
#define PAUSROOT 15  	/* OBJECT in TREE #3 */
#define YESPAUSE 17  	/* OBJECT in TREE #3 */
#define PRBKROOT 19  	/* OBJECT in TREE #3 */
#define SPRBKGND 20  	/* OBJECT in TREE #3 */
#define YESBKGND 21  	/* OBJECT in TREE #3 */
#define OKPRNT 23  	/* OBJECT in TREE #3 */
#define CANPRNT 24  	/* OBJECT in TREE #3 */
#define NUMPRTD 1  	/* OBJECT in TREE #4 */
#define CURPIC 2  	/* OBJECT in TREE #4 */
#define COPYPRTD 3  	/* OBJECT in TREE #4 */
#define TOTCNT 6  	/* OBJECT in TREE #4 */
#define ESCICON 7  	/* OBJECT in TREE #4 */
#define MISSITEM 4  	/* OBJECT in TREE #5 */
#define MISSDIR 6  	/* OBJECT in TREE #5 */
#define MISSCONT 7  	/* OBJECT in TREE #5 */
#define CMRAICN2 1  	/* OBJECT in TREE #6 */
#define FILMROOT 5  	/* OBJECT in TREE #6 */
#define FILMTYP0 6  	/* OBJECT in TREE #6 */
#define LGHTROOT 13  	/* OBJECT in TREE #6 */
#define DARKEN3 14  	/* OBJECT in TREE #6 */
#define FILMNAM0 21  	/* OBJECT in TREE #6 */
#define FILMNAMN 27  	/* OBJECT in TREE #6 */
#define OKFLMOPT 28  	/* OBJECT in TREE #6 */
#define CANFMOPT 29  	/* OBJECT in TREE #6 */
#define CMRAICN3 1  	/* OBJECT in TREE #7 */
#define COLIROOT 3  	/* OBJECT in TREE #7 */
#define CAMCOL00 4  	/* OBJECT in TREE #7 */
#define CAMCOL15 19  	/* OBJECT in TREE #7 */
#define COLSTR00 21  	/* OBJECT in TREE #7 */
#define COLNROOT 22  	/* OBJECT in TREE #7 */
#define COLWHITE 23  	/* OBJECT in TREE #7 */
#define COLPURPL 34  	/* OBJECT in TREE #7 */
#define COLSTR01 35  	/* OBJECT in TREE #7 */
#define SHADROOT 36  	/* OBJECT in TREE #7 */
#define LGTSHADE 37  	/* OBJECT in TREE #7 */
#define DRKSHADE 46  	/* OBJECT in TREE #7 */
#define COLSTR02 47  	/* OBJECT in TREE #7 */
#define OBJ2 48  	/* OBJECT in TREE #7 */
#define REDRGB 49  	/* OBJECT in TREE #7 */
#define GREENRGB 50  	/* OBJECT in TREE #7 */
#define BLUERGB 51  	/* OBJECT in TREE #7 */
#define COLSTR05 52  	/* OBJECT in TREE #7 */
#define COLSTR04 53  	/* OBJECT in TREE #7 */
#define COLSTR03 54  	/* OBJECT in TREE #7 */
#define OKCAMCOL 55  	/* OBJECT in TREE #7 */
#define CANCMCOL 56  	/* OBJECT in TREE #7 */
#define SGEMEXT 1  	/* OBJECT in TREE #8 */
#define SOPTEXT 2  	/* OBJECT in TREE #8 */
#define SLISEXT 3  	/* OBJECT in TREE #8 */
#define SPCLEXT 4  	/* OBJECT in TREE #8 */
#define SIMGEXT 5  	/* OBJECT in TREE #8 */
#define SUNTITLD 6  	/* OBJECT in TREE #8 */
#define SDEFAULT 7  	/* OBJECT in TREE #8 */
#define SAPPNAME 8  	/* OBJECT in TREE #8 */
#define PLOTICN2 1  	/* OBJECT in TREE #9 */
#define PLSCROOT 3  	/* OBJECT in TREE #9 */
#define OKPLOT 4  	/* OBJECT in TREE #9 */
#define CANPLOT 5  	/* OBJECT in TREE #9 */
#define PLOTFS 7  	/* OBJECT in TREE #9 */
#define DEVCROOT 1  	/* OBJECT in TREE #10 */
#define CMRAICON 6  	/* OBJECT in TREE #10 */
#define PRNTICON 7  	/* OBJECT in TREE #10 */
#define SCRNICON 8  	/* OBJECT in TREE #10 */
#define PLOTICON 9  	/* OBJECT in TREE #10 */
#define STRTPRNT 10  	/* OBJECT in TREE #10 */
#define STRTSCRN 11  	/* OBJECT in TREE #10 */
#define STRTPLOT 12  	/* OBJECT in TREE #10 */
#define STRTCMRA 13  	/* OBJECT in TREE #10 */
#define NUMCOPYS 2  	/* OBJECT in TREE #11 */
#define HORZROOT 3  	/* OBJECT in TREE #11 */
#define HORZLEFT 5  	/* OBJECT in TREE #11 */
#define VERTROOT 8  	/* OBJECT in TREE #11 */
#define VERTTOP 10  	/* OBJECT in TREE #11 */
#define DEFAROOT 13  	/* OBJECT in TREE #11 */
#define DEFAPRNT 15  	/* OBJECT in TREE #11 */
#define AUTOROOT 19  	/* OBJECT in TREE #11 */
#define AUTODYES 21  	/* OBJECT in TREE #11 */
#define OKPGOPT 23  	/* OBJECT in TREE #11 */
#define CANPGOPT 24  	/* OBJECT in TREE #11 */
#define FIL0NAME 1  	/* OBJECT in TREE #12 */
#define FILXNAME 24  	/* OBJECT in TREE #12 */
#define FIL0ITEM 26  	/* OBJECT in TREE #12 */
#define FILXITEM 49  	/* OBJECT in TREE #12 */
#define STRTSTR0 2  	/* OBJECT in TREE #13 */
#define STRTICON 3  	/* OBJECT in TREE #13 */
#define ADDSTR0 5  	/* OBJECT in TREE #13 */
#define DELESTR0 8  	/* OBJECT in TREE #13 */
#define DUPLSTR0 11  	/* OBJECT in TREE #13 */
#define STRTITEM 13  	/* OBJECT in TREE #13 */
#define ADDITEM 14  	/* OBJECT in TREE #13 */
#define DELEITEM 15  	/* OBJECT in TREE #13 */
#define DUPLITEM 16  	/* OBJECT in TREE #13 */
#define ALTICON1 2  	/* OBJECT in TREE #14 */
#define ALTICON2 3  	/* OBJECT in TREE #14 */
#define ALTICON3 4  	/* OBJECT in TREE #14 */
#define KEYAICON 5  	/* OBJECT in TREE #14 */
#define KEYCICON 6  	/* OBJECT in TREE #14 */
#define KEYDICON 7  	/* OBJECT in TREE #14 */
#define SHRTCANC 11  	/* OBJECT in TREE #14 */
#define ALTICON4 21  	/* OBJECT in TREE #14 */
#define KEYSICON 23  	/* OBJECT in TREE #14 */
#define PRNTICN3 4  	/* OBJECT in TREE #15 */
#define SCRNICN3 6  	/* OBJECT in TREE #15 */
#define PLOTICN3 8  	/* OBJECT in TREE #15 */
#define CMRAICN4 10  	/* OBJECT in TREE #15 */
#define SHRTOK 18  	/* OBJECT in TREE #15 */
#define HLOGOICN 1  	/* OBJECT in TREE #16 */
#define HGEMICON 2  	/* OBJECT in TREE #16 */
#define HOUT1ICN 3  	/* OBJECT in TREE #16 */
#define HOUT2ICN 4  	/* OBJECT in TREE #16 */
#define HPRNTICN 5  	/* OBJECT in TREE #16 */
#define HSCRNICN 6  	/* OBJECT in TREE #16 */
#define HPLOTICN 7  	/* OBJECT in TREE #16 */
#define HCMRAICN 8  	/* OBJECT in TREE #16 */
#define HSTRTICN 9  	/* OBJECT in TREE #16 */
#define HKEYAICN 10  	/* OBJECT in TREE #16 */
#define HKEYCICN 11  	/* OBJECT in TREE #16 */
#define HKEYDICN 12  	/* OBJECT in TREE #16 */
#define HKEYSICN 13  	/* OBJECT in TREE #16 */
#define HESCICON 14  	/* OBJECT in TREE #16 */
#define HALTICON 15  	/* OBJECT in TREE #16 */
#define CHGPAPER 0  	/* STRING */
#define DVCMISS 1  	/* STRING */
#define UNSVDCHG 2  	/* STRING */
#define NOTLIST 3  	/* STRING */
#define NOOVLERR 4  	/* STRING */
#define PRNTFILM 5  	/* STRING */
#define NODSPACE 6  	/* STRING */
#define DRKSLIDE 7  	/* STRING */
#define REPLACEF 8  	/* STRING */
#define NOSTART 9  	/* STRING */
