/*----------------------------------------------------------------------*/
/* The source code contained in this listing is a non-copyrighted	*/
/* work which can be freely used. In applications of the source code	*/
/* you are requested to acknowledge Digital Research, Inc. as the	*/
/* originator of this code.						*/
/*----------------------------------------------------------------------*/

/*----------------------------------------------------------------------*/
/* xlib.h - includes for transformation library.			*/
/*----------------------------------------------------------------------*/

EXTERN WORD	x_ytox() ;
EXTERN WORD	x_udx_xform() ;
EXTERN WORD	x_udy_xform() ;
EXTERN WORD	x_dux_xform() ;
EXTERN WORD	x_duy_xform() ;
EXTERN WORD	x_udx_scale() ;
EXTERN WORD	x_udy_scale() ;
EXTERN WORD	x_dux_scale() ;
EXTERN WORD	x_duy_scale() ;
EXTERN VOID	x_sxform() ;
EXTERN VOID	x_saspect() ;
