#define MAINMENU 0  	/* TREE */
#define QUITITEM 17  	/* OBJECT in TREE #0 */
#define ABOUITEM 8  	/* OBJECT in TREE #0 */
#define VIEWITEM 19  	/* OBJECT in TREE #0 */
#define NWINDOW 0  	/* STRING */
#define ABOUDIAL 1  	/* TREE */
#define ABOUOK 2  	/* OBJECT in TREE #1 */
#define FITDIAL 2  	/* TREE */
#define FULLITEM 2  	/* OBJECT in TREE #2 */
#define SVASITEM 11  	/* OBJECT in TREE #2 */
#define IGASITEM 13  	/* OBJECT in TREE #2 */
#define FITOK 15  	/* OBJECT in TREE #2 */
#define ZOM2ITEM 5  	/* OBJECT in TREE #2 */
#define ZOM3ITEM 8  	/* OBJECT in TREE #2 */
