#define AL00CRT 30  	/* STRING */
#define AL01CRT 31  	/* STRING */
#define AL02CRT 32  	/* STRING */
#define AL03CRT 33  	/* STRING */
#define AL04CRT 34  	/* STRING */
#define AL05CRT 35  	/* STRING */
#define AL18ERR 36  	/* STRING */
#define ALNOFIT 37  	/* STRING */
#define AL04ERR 38  	/* STRING */
#define AL05ERR 39  	/* STRING */
#define AL15ERR 40  	/* STRING */
#define AL16ERR 41  	/* STRING */
#define AL08ERR 42  	/* STRING */
#define ALXXERR 43  	/* STRING */
#define ALNOFUNC 44  	/* STRING */
#define ALOKDESK 45  	/* STRING */
#define DIALERT 1  	/* TREE */
#define DESKTOP 2  	/* TREE */
#define STPATH 0		/* FREE STRING */
#define STDESKTP 1		/* FREE STRING */
#define STGEM 2		/* FREE STRING */
#define STACC 3		/* FREE STRING */
#define ST9VAL 4		/* FREE STRING */
#define STAVAL 5		/* FREE STRING */
#define STNVAL 6		/* FREE STRING */
#define STPVAL 7		/* FREE STRING */
#define STLPVAL 8		/* FREE STRING */
#define STFVAL 9		/* FREE STRING */
#define STLFAVAL 10		/* FREE STRING */
#define STLAVAL 11		/* FREE STRING */
#define STSCDIR 15		/* FREE STRING */
#define STINPATH 14		/* FREE STRING */
#define STGDOS 13		/* FREE STRING */
#define STLNVAL 12		/* FREE STRING */
#define NOTEBB 0		/* FREE IMAGE */
#define QUESTBB 1		/* FREE IMAGE */
#define STOPBB 2		/* FREE IMAGE */
#define MICE00 3		/* FREE IMAGE */
#define MICE01 4		/* FREE IMAGE */
#define MICE02 5		/* FREE IMAGE */
#define MICE03 6		/* FREE IMAGE */
#define MICE04 7		/* FREE IMAGE */
#define MICE05 8		/* FREE IMAGE */
#define MICE06 9		/* FREE IMAGE */
#define MICE07 10		/* FREE IMAGE */
#define MSGOFF 2  	/* OBJECT in TREE #1 */
#define BUTOFF 7  	/* OBJECT in TREE #1 */
#define STVERSN 16		/* FREE STRING */
#define STAVAIL 17		/* FREE STRING */
#define STSCREEN 18		/* FREE STRING */
#define STINFPAT 19		/* FREE STRING */
#define STSCRAP 20		/* FREE STRING */
#define ISELNAME 21		/* FREE STRING */
#define STCFGPAT 22		/* FREE STRING */
#define STTMPPAT 23		/* FREE STRING */
#define PROPAES 24		/* FREE STRING */
#define PROPCLR 25		/* FREE STRING */
#define PROPBUTN 26		/* FREE STRING */
#define PROP2D 27		/* FREE STRING */
#define CLRUI 3  	/* TREE */
#define MONOUI 4  	/* TREE */
#define CTICK 2  	/* OBJECT in TREE #3 */
#define CCROSS 3  	/* OBJECT in TREE #3 */
#define CDOT 4  	/* OBJECT in TREE #3 */
#define CCIRC 5  	/* OBJECT in TREE #3 */
#define CDFLT 6  	/* OBJECT in TREE #3 */
#define MTICK 2  	/* OBJECT in TREE #4 */
#define MCROSS 3  	/* OBJECT in TREE #4 */
#define MDOT 4  	/* OBJECT in TREE #4 */
#define MCIRC 5  	/* OBJECT in TREE #4 */
#define MDFLT 6  	/* OBJECT in TREE #4 */
#define CSQUARE 7  	/* OBJECT in TREE #3 */
#define FSELECTR 0  	/* TREE */
#define FSDIRECT 8  	/* OBJECT in TREE #0 */
#define FSSELECT 6  	/* OBJECT in TREE #0 */
#define FCLSBOX 16  	/* OBJECT in TREE #0 */
#define FILEBOX 17  	/* OBJECT in TREE #0 */
#define F1NAME 18  	/* OBJECT in TREE #0 */
#define F2NAME 19  	/* OBJECT in TREE #0 */
#define F3NAME 20  	/* OBJECT in TREE #0 */
#define F4NAME 21  	/* OBJECT in TREE #0 */
#define F5NAME 22  	/* OBJECT in TREE #0 */
#define F6NAME 23  	/* OBJECT in TREE #0 */
#define F7NAME 24  	/* OBJECT in TREE #0 */
#define F8NAME 25  	/* OBJECT in TREE #0 */
#define F9NAME 26  	/* OBJECT in TREE #0 */
#define FUPAROW 13  	/* OBJECT in TREE #0 */
#define FDNAROW 12  	/* OBJECT in TREE #0 */
#define FSVSLID 14  	/* OBJECT in TREE #0 */
#define FSVELEV 15  	/* OBJECT in TREE #0 */
#define FSOK 1  	/* OBJECT in TREE #0 */
#define FSCANCEL 2  	/* OBJECT in TREE #0 */
#define SCRLBAR 11  	/* OBJECT in TREE #0 */
#define FTITLE 10  	/* OBJECT in TREE #0 */
#define NFSTITLE 4  	/* OBJECT in TREE #0 */
#define PROPSHEL 28		/* FREE STRING */
#define PROPGOPT 29		/* FREE STRING */
#define FSDRIVES 7  	/* OBJECT in TREE #0 */
