#define MAINMENU 0  	/* TREE */
#define EDITMENU 5  	/* OBJECT in TREE #0 */
#define FILEMENU 4  	/* OBJECT in TREE #0 */
#define FILEQUIT 20  	/* OBJECT in TREE #0 */
#define FILEOPEN 21  	/* OBJECT in TREE #0 */
#define FILENEW 22  	/* OBJECT in TREE #0 */
#define FILESAVE 23  	/* OBJECT in TREE #0 */
#define SAVEAS 24  	/* OBJECT in TREE #0 */
#define EDITCOPY 27  	/* OBJECT in TREE #0 */
#define EDITPAST 28  	/* OBJECT in TREE #0 */
#define EDITCUT 29  	/* OBJECT in TREE #0 */
#define APPABOUT 11  	/* OBJECT in TREE #0 */
#define DESKMENU 3  	/* OBJECT in TREE #0 */
#define SETTINGS 1  	/* TREE */
#define OKBTN 1  	/* OBJECT in TREE #1 */
#define CANCEL 2  	/* OBJECT in TREE #1 */
#define ICONDATA 2  	/* TREE */
#define EDCAPTN 2  	/* OBJECT in TREE #2 */
#define GROUPBOX 1  	/* OBJECT in TREE #2 */
#define PREVWICN 6  	/* OBJECT in TREE #2 */
#define CAPTIONU 28  	/* OBJECT in TREE #2 */
#define CAPTIOND 29  	/* OBJECT in TREE #2 */
#define ICONU 15  	/* OBJECT in TREE #2 */
#define ICOND 19  	/* OBJECT in TREE #2 */
#define ICONL 17  	/* OBJECT in TREE #2 */
#define ICONR 16  	/* OBJECT in TREE #2 */
#define BTNOK 36  	/* OBJECT in TREE #2 */
#define BTNCANCL 37  	/* OBJECT in TREE #2 */
#define BTNHELP 38  	/* OBJECT in TREE #2 */
#define BITMAPED 4  	/* TREE */
#define GRIDBOX 1  	/* OBJECT in TREE #4 */
#define PREVIEW 12  	/* OBJECT in TREE #4 */
#define ABOUTBOX 5  	/* TREE */
#define BTNOK2 1  	/* OBJECT in TREE #5 */
#define NOWING 0  	/* STRING */
#define NOWINE 1  	/* STRING */
#define APPICON 4  	/* OBJECT in TREE #5 */
#define ASKSAVE 2  	/* STRING */
#define HREFLECT 21  	/* OBJECT in TREE #2 */
#define VREFLECT 20  	/* OBJECT in TREE #2 */
#define LETTERU 10  	/* OBJECT in TREE #2 */
#define LETTERR 11  	/* OBJECT in TREE #2 */
#define LETTERL 12  	/* OBJECT in TREE #2 */
#define LETTERD 13  	/* OBJECT in TREE #2 */
#define ROTATER 18  	/* OBJECT in TREE #2 */
#define ROTATEL 22  	/* OBJECT in TREE #2 */
#define INVERTIC 23  	/* OBJECT in TREE #2 */
#define EDITC 24  	/* OBJECT in TREE #2 */
#define EDITX 25  	/* OBJECT in TREE #2 */
#define EDITP 26  	/* OBJECT in TREE #2 */
#define WNDMENU 8  	/* OBJECT in TREE #0 */
#define WNDTILE 54  	/* OBJECT in TREE #0 */
#define WNDCASC 55  	/* OBJECT in TREE #0 */
#define EDITOR 7  	/* OBJECT in TREE #2 */
#define CBLACK 32  	/* OBJECT in TREE #2 */
#define CWHITE 34  	/* OBJECT in TREE #2 */
#define TWHITE 35  	/* OBJECT in TREE #2 */
#define TBLACK 33  	/* OBJECT in TREE #2 */
#define PREVWBOX 3  	/* OBJECT in TREE #2 */
#define ALREADY 3  	/* STRING */
#define PREVWDSK 5  	/* OBJECT in TREE #2 */
#define NEWFILE 6  	/* TREE */
#define BTNOK4 10  	/* OBJECT in TREE #6 */
#define BTNCAN4 9  	/* OBJECT in TREE #6 */
#define DESKLO 5  	/* OBJECT in TREE #6 */
#define WINHI 6  	/* OBJECT in TREE #6 */
#define WINLO 7  	/* OBJECT in TREE #6 */
#define WINDBL 8  	/* OBJECT in TREE #6 */
#define SAVEFMT 7  	/* TREE */
#define WINICO 5  	/* OBJECT in TREE #7 */
#define GEMICN 4  	/* OBJECT in TREE #7 */
#define GEMRCS 6  	/* OBJECT in TREE #7 */
#define DESKHI 4  	/* OBJECT in TREE #6 */
#define BTNOK5 8  	/* OBJECT in TREE #7 */
#define BTNCAN5 7  	/* OBJECT in TREE #7 */
#define NOICOS 4  	/* STRING */
#define CONTROLS 2  	/* OBJECT in TREE #4 */
#define PALETTE 3  	/* OBJECT in TREE #4 */
#define EDITNAME 8  	/* OBJECT in TREE #4 */
#define CLR1 4  	/* OBJECT in TREE #4 */
#define CLR2 5  	/* OBJECT in TREE #4 */
#define CLR3 6  	/* OBJECT in TREE #4 */
#define CLR4 7  	/* OBJECT in TREE #4 */
#define IMGMENU 6  	/* OBJECT in TREE #0 */
#define REFLECTH 33  	/* OBJECT in TREE #0 */
#define REFLECTV 34  	/* OBJECT in TREE #0 */
#define ROTATEC 36  	/* OBJECT in TREE #0 */
#define ROTATEA 37  	/* OBJECT in TREE #0 */
#define MOVEU 39  	/* OBJECT in TREE #0 */
#define MOVED 40  	/* OBJECT in TREE #0 */
#define MOVERR 41  	/* OBJECT in TREE #0 */
#define MOVEL 42  	/* OBJECT in TREE #0 */
#define PREVIEWB 11  	/* OBJECT in TREE #4 */
#define IMGINV 44  	/* OBJECT in TREE #0 */
#define ICONNAME 3  	/* TREE */
#define ENOK 1  	/* OBJECT in TREE #3 */
#define ENCANCEL 2  	/* OBJECT in TREE #3 */
#define EDITTTL 4  	/* OBJECT in TREE #3 */
#define EDNBTN 13  	/* OBJECT in TREE #4 */
#define CAPTMENU 7  	/* OBJECT in TREE #0 */
#define CAPTUP 47  	/* OBJECT in TREE #0 */
#define CAPTDOWN 48  	/* OBJECT in TREE #0 */
#define LTRUP 49  	/* OBJECT in TREE #0 */
#define LTRDN 50  	/* OBJECT in TREE #0 */
#define LTRRT 51  	/* OBJECT in TREE #0 */
#define LTRLT 52  	/* OBJECT in TREE #0 */
#define NOT72 5  	/* STRING */
#define NOT1 6  	/* STRING */
#define FGBTN 14  	/* OBJECT in TREE #4 */
#define BGBTN 15  	/* OBJECT in TREE #4 */
#define CHCOL1 8  	/* OBJECT in TREE #1 */
#define CHCOL2 9  	/* OBJECT in TREE #1 */
#define CHCOL3 10  	/* OBJECT in TREE #1 */
#define CHCOL4 11  	/* OBJECT in TREE #1 */
#define CHCOL5 13  	/* OBJECT in TREE #1 */
#define CHSHD5 14  	/* OBJECT in TREE #1 */
#define EDITSET 31  	/* OBJECT in TREE #0 */
#define CHSHD1 17  	/* OBJECT in TREE #1 */
#define CHSHD2 18  	/* OBJECT in TREE #1 */
#define CHSHD3 19  	/* OBJECT in TREE #1 */
#define CHSHD4 20  	/* OBJECT in TREE #1 */
#define FILEFULL 7  	/* STRING */
