;/*	PROEND.A86		4/18/84 - 4/18/84	Lee Lorenzen	*/
;
;
;
;
;       Copyright 1999, Caldera Thin Clients, Inc.                      
;       This software is licenced under the GNU Public License.         
;       Please see LICENSE.TXT for further information.                 
;                                                                       
;                  Historical Copyright                                 
;/*
;*	-------------------------------------------------------------
;*	GEM Application Environment Services		  Version 2.3
;*	Serial No.  XXXX-0000-654321		  All Rights Reserved
;*	Copyright (C) 1986			Digital Research Inc.
;*	-------------------------------------------------------------
;*/
;
	.psect	bss,class=BSS
;
;
	.globl	_PROGEND
;
;
_PROGEND:
	.word	0
;

