#define STNODEF 17  	/* STRING */
#define STMOVED 18  	/* STRING */
#define STLOMEM 19  	/* STRING */
#define STNMDUP 20  	/* STRING */
#define STNONAM 21  	/* STRING */
#define STLOCKED 22  	/* STRING */
#define STSIZEP 23  	/* STRING */
#define STNFULL 24  	/* STRING */
#define STPANIC 25  	/* STRING */
#define STNROOM 26  	/* STRING */
#define ALERT27 27  	/* STRING */
#define ALERT28 28  	/* STRING */
#define ALERT29 29  	/* STRING */
#define ALERT30 30  	/* STRING */
#define ALERT31 31  	/* STRING */
#define ABNDCHGS 32  	/* STRING */
#define ALERT33 33  	/* STRING */
#define NOEDMEM 34  	/* STRING */
#define MENUTREE 0  	/* TREE */
#define TOOLBOX 1  	/* TREE */
#define FILEPBX 2  	/* TREE */
#define TYPETREE 3  	/* TREE */
#define DIALPBX 4  	/* TREE */
#define ICNPBX 5  	/* TREE */
#define NOBJTREE 6  	/* TREE */
#define MENUPBX 7  	/* TREE */
#define NEWMENU 8  	/* TREE */
#define ABOUTREE 9  	/* TREE */
#define SORTTREE 10  	/* TREE */
#define NEWALRT 11  	/* TREE */
#define ALRTPBX 12  	/* TREE */
#define NEWDIAL 13  	/* TREE */
#define NEWPANEL 14  	/* TREE */
#define OUTPTREE 15  	/* TREE */
#define STRDIAL 16  	/* TREE */
#define BITDIAL 17  	/* TREE */
#define ICONDIAL 18  	/* TREE */
#define BOXDIAL 19  	/* TREE */
#define TEXTDIAL 20  	/* TREE */
#define LOADDIAL 21  	/* TREE */
#define SAFEDIAL 22  	/* TREE */
#define INFODIAL 23  	/* TREE */
#define ICONTOOL 24  	/* TREE */
#define FREEPBX 25  	/* TREE */
#define POPSWTCH 26  	/* TREE */
#define TREE28 27  	/* TREE */
#define TREE29 28  	/* TREE */
#define TREE30 29  	/* TREE */
#define TREE31 30  	/* TREE */
#define TREE32 31  	/* TREE */
#define TREE33 32  	/* TREE */
#define TREE34 33  	/* TREE */
#define GRID 34  	/* TREE */
#define NEWICNSZ 35  	/* TREE */
#define SBLEPOP 1  	/* OBJECT in TREE #26 */
#define EXITPOP 2  	/* OBJECT in TREE #26 */
#define DFLTPOP 3  	/* OBJECT in TREE #26 */
#define RDIOPOP 4  	/* OBJECT in TREE #26 */
#define TCHXPOP 5  	/* OBJECT in TREE #26 */
#define EDBLPOP 6  	/* OBJECT in TREE #26 */
#define SHADPOP 9  	/* OBJECT in TREE #26 */
#define CHEKPOP 10  	/* OBJECT in TREE #26 */
#define OUTLPOP 11  	/* OBJECT in TREE #26 */
#define CROSSPOP 12  	/* OBJECT in TREE #26 */
#define DSBLPOP 13  	/* OBJECT in TREE #26 */
#define SLCTPOP 14  	/* OBJECT in TREE #26 */
#define HDDNPOP 7  	/* OBJECT in TREE #26 */
#define D3DPOP 15  	/* OBJECT in TREE #26 */
#define CCLRPOP 16  	/* OBJECT in TREE #26 */
#define ABOUITEM 11  	/* OBJECT in TREE #0 */
#define FILEMENU 4  	/* OBJECT in TREE #0 */
#define OPTNMENU 7  	/* OBJECT in TREE #0 */
#define GLOBMENU 5  	/* OBJECT in TREE #0 */
#define NEWITEM 20  	/* OBJECT in TREE #0 */
#define OPENITEM 21  	/* OBJECT in TREE #0 */
#define MERGITEM 22  	/* OBJECT in TREE #0 */
#define CLOSITEM 24  	/* OBJECT in TREE #0 */
#define SAVEITEM 25  	/* OBJECT in TREE #0 */
#define SVASITEM 26  	/* OBJECT in TREE #0 */
#define RVRTITEM 27  	/* OBJECT in TREE #0 */
#define QUITITEM 29  	/* OBJECT in TREE #0 */
#define INFOITEM 48  	/* OBJECT in TREE #0 */
#define OUTPITEM 31  	/* OBJECT in TREE #0 */
#define SAFEITEM 32  	/* OBJECT in TREE #0 */
#define DESKMENU 3  	/* OBJECT in TREE #0 */
#define PANLICON 4  	/* OBJECT in TREE #2 */
#define MENUICON 2  	/* OBJECT in TREE #2 */
#define DIALICON 3  	/* OBJECT in TREE #2 */
#define ALRTICON 5  	/* OBJECT in TREE #2 */
#define UNKNITEM 9  	/* OBJECT in TREE #3 */
#define PANLITEM 10  	/* OBJECT in TREE #3 */
#define MENUITEM 11  	/* OBJECT in TREE #3 */
#define DIALITEM 12  	/* OBJECT in TREE #3 */
#define ALRTITEM 13  	/* OBJECT in TREE #3 */
#define FREEITEM 14  	/* OBJECT in TREE #3 */
#define OKITEM 6  	/* OBJECT in TREE #3 */
#define CANCITEM 7  	/* OBJECT in TREE #3 */
#define NOOKITEM 2  	/* OBJECT in TREE #6 */
#define NOCNITEM 3  	/* OBJECT in TREE #6 */
#define ESCCPOP 17  	/* OBJECT in TREE #26 */
#define SCRCPOP 18  	/* OBJECT in TREE #26 */
#define HILIPOP 19  	/* OBJECT in TREE #26 */
#define UNHIPOP 20  	/* OBJECT in TREE #26 */
