#define FAR  
#define NEAR 

#define LPVOID LONG	/* Some pseudo-types to make it easier to see */
#define LPLPTR LONG     /* what the parameters passed are */
#define LPBYTE LONG
#define LPWORD LONG
#define LPLONG LONG
#define LPUWORD LONG

#define LPOBJ   LONG	/* Pointers to more complicated objects */
#define LPTREE  LONG
#define LPORECT LONG
#define LPGRECT LONG
#define LPTEDI  LONG
#define LPICON  LONG
#define LPBIT   LONG
#define LPUSER  LONG
#define LPAPPL  LONG
#define LPPARM  LONG
#define LPMFDB  LONG
#define LPFILL  LONG


#include "machin32.h"
