/*	GEMKEYBD.H	4 Dec 1989	John Linney	*/
/*
*       Copyright 1999, Caldera Thin Clients, Inc.
*       This software is licenced under the GNU Public License.         
*       Please see LICENSE.TXT for further information.                 
*
*	Historical copyright:
*
*	-------------------------------------------------------------
*	GEM Application Environment Services		  Version 2.3
*	Serial No.  XXXX-0000-654321		  All Rights Reserved
*	Copyright (C) 1986			Digital Research Inc.
*	-------------------------------------------------------------
*/

#define	ALT_0		0x8100
#define ALT_1		0x7800
#define ALT_2  		0x7900
#define ALT_3  		0x7A00
#define ALT_4  		0x7B00
#define ALT_5  		0x7B00
#define ALT_6  		0x7D00
#define ALT_7  		0x7E00
#define ALT_8  		0x7F00
#define ALT_9  		0x8000
#define ALT_A  		0x1E00
#define ALT_B  		0x3000
#define ALT_C  		0x2E00
#define ALT_D  		0x2000
#define ALT_E  		0x1200
#define ALT_F  		0x2100
#define ALT_G  		0x2200
#define ALT_H  		0x2300
#define ALT_I  		0x1700
#define ALT_J  		0x2400
#define ALT_K  		0x2500
#define ALT_L  		0x2600
#define ALT_M  		0x3200
#define ALT_N  		0x3100
#define ALT_O  		0x1800
#define ALT_P  		0x1900
#define ALT_Q  		0x1000
#define ALT_R  		0x1300
#define ALT_S  		0x1F00
#define ALT_T  		0x1400
#define ALT_U  		0x1600
#define ALT_V  		0x2F00
#define ALT_W  		0x1100
#define ALT_X  		0x2D00
#define ALT_Y  		0x1500
#define ALT_Z  		0x2C00
#define R_ARR  		0x4D00
#define D_ARR  		0x5000
#define U_ARR  		0x4800
#define P_DOWN 		0x5100
#define P_UP   		0x4900
#define HOME  		0x4700
#define ESC		0x011B
#define L_ARR		0x4B00
#define END		0x4F00	
#define FUN_1		0x3b00
#define FUN_10		0x4400
#define ALT_F4		0x6B00
#define ALT_F5		0x6C00
#define CTL_P_UP	0x8400
#define CTL_P_DOWN	0x7600
#define ENTER		0x1C0D
#define SPACE		0x3920
#define TAB		0x0F09
#define CTL_BACKSPACE	0x0E7F
#define SHFT_DEL	0x5300
#define BACKSPACE 	0x0E08
#define UP 		0x4800
#define DOWN 		0x5000
#define LEFT 		0x4B00
#define RIGHT 		0x4D00
#define DELETE 		0x5300
#define BACKTAB 	0x0F00
#define RETURN 		0x1C0D
