
CC     = gcc
CFLAGS = -I../../include
LIBS   = -L../../lib -lgem
CP     = copy
RM     = xdel /n

TARGET=prop

all:	$(TARGET).app

$(TARGET).app:	$(TARGET).exe
	$(CP) $(TARGET).exe $(TARGET).app
	$(CP) $(TARGET).app ..\..\bin

$(TARGET).exe:	$(TARGET).o
	$(CC) -o $(TARGET) $< $(LIBS)

tidy:
	-$(RM) *.bak
	-$(RM) $(TARGET).o
	-$(RM) $(TARGET).exe
	-$(RM) $(TARGET)

clean:	tidy
	-$(RM) $(TARGET).app
